#!/bin/sh
# ============================================================================
# test ups depend
# ============================================================================
cd $UPS_DIR/test/scripts/depend/log
$UPS_DIR/test/ups_test << EOD 
depend bee3 v2_0 -f NULL -z ../db1 -K DECLARER:VERSION:PRODUCT -out bee1.out -diff bee1.in
depend bee3 v2_0 -f NULL -z ../db1 -K Blah -status UPS_INVALID_KEYWORD -out bee4.out -diff bee4.in
depend bee3 v2_0 -f NULL -z ../db1 -m bee5.table -out bee2.out -diff bee2.in
depend bee3 v2_0 -f NULL -z ../db1 -M ../db1/bee3 -out bee3.out -diff bee3.in
quit
EOD
