#!/bin/sh
# ============================================================================
# test the match routines
# ============================================================================
unset PRODUCTS
cd $UPS_DIR/test/scripts/match/log
$UPS_DIR/test/ups_test << EOD
#ups_echo "================================================================="
#
# see if things work without a table file specified
#
# these two things no longer return an error
#upsmat_instance -status UPS_DB_CORRUPTION -z ../db0 notable v2_0
#upsmat_instance -out notable1.out -diff notable1.in -status UPS_DB_CORRUPTION -z ../db0 notable -a
upsmat_instance -out notable2.out -diff notable2.in -z ../db0 notable v1_0
# 
# simple tests with rover
#
upsmat_instance -out rover1.out -diff rover1.in -z ../db1 -a rover v2_0 
upsmat_instance -out rover2.out -diff rover2.in -z ../db1 -H IRIX+5.3 -a -q"+nodbg:+opt" rover v2_0
upsmat_instance -out rover3.out -diff rover3.in -z ../db1 -H IRIX+5.3 -a -q"+nodbg:+opt" rover v2_0 -unique
upsmat_instance -out rover4.out -diff rover4.in -z ../db1 -H IRIX+5.3.1 -q"+nodbg:+opt" rover v2_0 -unique
upsmat_instance -out rover4.out -diff rover4.in -z ../db1 -f IRIX+5.3 -q"+nodbg:+opt" rover v2_0 -unique
#
# table file tests with spot
#
upsmat_instance -out spot1.out -diff spot1.in -H IRIX+5 -m ../db1/spot/spot.table -q"+nodbg:+opt" spot
upsmat_instance -out spot1.out -diff spot1.in -H IRIX+5 -M ../db1/spot -m spot.table -q"+nodbg:+opt" spot
upsmat_instance -out spot2.out -diff spot2.in -H IRIX+5 -m ../db1/spot/spot.table -q"+nodbg:+opt" -unique spot
#
# chain tests with lassie
#
upsmat_instance -out lassie0.out -diff lassie0.in -z ../db1 -H IRIX+5 -a lassie
upsmat_instance -out lassie1.out -diff lassie1.in -z ../db1 -H IRIX+5 -a -c lassie
upsmat_instance -out lassie1.out -diff lassie1.in -z ../db1 -H IRIX+5 -a -g current lassie
upsmat_instance -out lassie2.out -diff lassie2.in -z ../db1 -H IRIX+5 -a -g current:test lassie
upsmat_instance -out lassie3.out -diff lassie3.in -z ../db1 -H IRIX+5 -a -t lassie
upsmat_instance -out lassie4.out -diff lassie4.in -z ../db1 -H IRIX+5 -c -q"+nodbg:+opt" -unique lassie
upsmat_instance -out lassie5.out -diff lassie5.in -z ../db1 -H IRIX+5 -g mydog  -q"+nodbg:+opt" -unique lassie
#
# qualifier tests with snoopy
#
upsmat_instance -out snoopy1.out -diff snoopy1.in -z ../db1 -H IRIX+5 snoopy v1_0 -a
upsmat_instance -out snoopy2.out -diff snoopy2.in -z ../db1 -H IRIX+5 snoopy v1_0 -q ?pigpen
upsmat_instance -out snoopy3.out -diff snoopy3.in -z ../db1 -H IRIX+5 snoopy v1_0 -q +pigpen
upsmat_instance -out snoopy4.out -diff snoopy4.in -z ../db1 -H IRIX+5 snoopy v1_0 -q ?pigpen -unique
upsmat_instance -out snoopy5.out -diff snoopy5.in -z ../db1 -H IRIX+5 snoopy v1_0 -q +lucy:+linus:+pigpen:+violet 
#
# flavor = ANY tests with 
#
upsmat_instance -z ../db1 -f YAHOO  -unique benji v1_0 -out benji1.out -diff benji1.in
upsmat_instance -z ../db1 -f IRIX+5 -unique benji v1_0 -out benji2.out -diff benji2.in
#
# multiple db tests
#
upsmat_instance -out lassie6.out -diff lassie6.in -z ../db1:../db2 -f NULL -a lassie v2_0
upsmat_instance -out lassie7.out -diff lassie7.in -z ../db1:../db2 -f NULL -q +nodbg:+opt lassie v2_0 -unique
upsmat_instance -out asta1.out -diff asta1.in -z ../db1:../db2 -f NULL -a asta
upsmat_instance -out asta2.out -diff asta2.in -z ../db1:../db2 -f NULL -a 
upsmat_instance -out asta3.out -diff asta3.in -z ../db1:../db2 -f NULL -a -db ../db2
upsmat_instance -out asta4.out -diff asta4.in -z ../db0:../db1:../db2 -f NULL -a -status UPS_DB_CORRUPTION
#
# test a nonexistent database
#
upsmat_instance -z dummy dog -status UPS_NOT_A_DIR
quit
EOD
