#!/bin/sh
# ============================================================================
# test ups start
# ============================================================================
cd $UPS_DIR/test/scripts/start/log
SHELL=sh;export SHELL;
UPS_SHELL=${SHELL};export UPS_SHELL;
env PRODUCTS=../db1 $UPS_DIR/test/ups_test << EOD
start penguin -g current -M ../db1/penguin -m penguin.table -z ../db1 -actout tmp1.out -out penguin1.out -diff penguin1.in
start penguin v2_0 -q ralph -r ../db1 -actout tmp2.out -out penguin2.out -diff penguin2.in
start penguin v2_0 -q ralph -w -z ../db1 -actout tmp3.out -out penguin3.out -diff penguin3.in 
start penguin v2_0 -q ralph -s -n
start penguin v2_0 -q ralph -s -o
start penguin v2_0 -q ralph -s -t
start penguin v2_0 -q ralph -s -V -U /NULL/blah
start kerplop -status UPS_SUCCESS
quit
EOD
