#!/bin/sh
echo "======================================================================"
echo "Testing error routines"
upstst_error
echo "======================================================================"
echo "Testing file routines"
upstst_file
echo "======================================================================"
echo "Testing ugo routines"
upstst_ugo
echo "======================================================================"
echo "Testing match routines"
upstst_match
echo "======================================================================"
echo "Testing ups_list"
upstst_list
echo "======================================================================"
echo "Testing get routines "
upstst_get
echo "======================================================================"
echo "Testing action routines"
upstst_action
echo "======================================================================"
echo "Testing declare routines"
upstst_declare
echo "======================================================================"
echo "Testing undeclare routines"
upstst_undeclare
echo "======================================================================"
echo "Testing depend routines"
upstst_depend
echo "======================================================================"
echo "Testing copy routines"
upstst_copy
echo "======================================================================"
echo "Testing compile routines"
upstst_compile
echo "======================================================================"
echo "Testing configure routines"
upstst_configure
echo "======================================================================"
echo "Testing unconfigure routines"
upstst_unconfigure
echo "======================================================================"
echo "Testing tailor routines"
upstst_tailor
echo "======================================================================"
echo "Testing start routines"
upstst_start
echo "======================================================================"
echo "Testing stop routines"
upstst_stop
echo "======================================================================"
echo "Testing exist command"
upstst_exist
echo "======================================================================"
echo "Testing -B flag"
upstst_Bflag
echo "======================================================================"
echo "Testing ignoring editor temp files"
upstst_edittmp
