#!/bin/sh
# ============================================================================
# test ups declare
# ============================================================================
PRODUCTS="$UPS_DIR/test/scripts/declare/dbclean"; export PRODUCTS
rm -rf $PRODUCTS
rm -rf $UPS_DIR/test/scripts/declare/tostuff
rm -rf $UPS_DIR/test/scripts/declare/products/spot/ups/toinfo
mkdir $UPS_DIR/test/scripts/declare/products/spot/ups/toinfo
# should make full path for tostuff..
cp $UPS_DIR/test/scripts/declare/products/spot/ups/source_info/info.file \
   $UPS_DIR/test/scripts/declare/products/spot/ups/toinfo 
mkdir $PRODUCTS
mkdir $PRODUCTS/.upsfiles
cp $UPS_DIR/test/scripts/declare/dbcmp/.upsfiles/dbconfig $PRODUCTS/.upsfiles
cd $UPS_DIR/test/scripts/declare
$UPS_DIR/test/ups_test << EOD
#
#
declare rover -status UPS_INVALID_SPECIFICATION 
declare rover v1_0 -f NULL -r /tmp
declare rover v1_0 -f NULL -r /tmp -status UPS_INVALID_SPECIFICATION
declare rover v1_0 -f IRIX -g leash -r /tmp
declare rover v1_0 -g leash -H IRIX
upserr_clear
#
# test most switches
#
declare rover v2_0 -f NULL -A backyard -b mycompile -D akc@kennel -g leash -L -m tablefile -M /tabledir -O "-blah" -q"red" -r /dog/house -T ftp:/tarfile -u /tmp -U /ups 
#
# make sure actions are executed
#

declare spot v1_0 -f NULL -r \${UPS_DIR}/test/scripts/declare/products/spot -M ups -m spot.table -c -d -o -t -n -g leash -actout log/tmp.out -out log/spot1.out -diff log/spot1.in 
declare spot v1_0 -f NULL -c -d -o -t -n -g leash -actout log/tmp.out -out log/spot2.out -diff log/spot2.in 

declare spot v2_0 -f IRIX -r \${UPS_DIR}/test/scripts/declare/products/spot -C -c -M ups -m spot.table -T ftp://sillyhostname\${UPS_DIR}/test/scripts/declare/products/spot/archive.file
quit
EOD
ls tostuff/*/* > log/tostuff.out
diff dbclean/rover/leash.chain dbcmp/rover | egrep -i "<|>|diff" | egrep -i -v "DECLARE|MODIF" 
diff dbclean/rover/v1_0.version dbcmp/rover | egrep -i "<|>|diff" | egrep -i -v "DECLARE|MODIF" 
diff dbclean/rover/v2_0.version dbcmp/rover | egrep -i "<|>|diff" | egrep -i -v "DECLARE|MODIF" 
diff dbclean/spot/current.chain dbcmp/spot | egrep -i "<|>|diff" | egrep -i -v "DECLARE|MODIF" 
diff dbclean/spot/new.chain dbcmp/spot | egrep -i "<|>|diff" | egrep -i -v "DECLARE|MODIF" 
diff dbclean/spot/old.chain dbcmp/spot | egrep -i "<|>|diff" | egrep -i -v "DECLARE|MODIF" 
diff dbclean/spot/test.chain dbcmp/spot | egrep -i "<|>|diff" | egrep -i -v "DECLARE|MODIF" 
diff dbclean/spot/leash.chain dbcmp/spot | egrep -i "<|>|diff" | egrep -i -v "DECLARE|MODIF" 
diff dbclean/spot/v1_0.version dbcmp/spot | egrep -i "<|>|diff" | egrep -i -v "DECLARE|MODIF" 
diff dbclean/spot/v2_0.version dbcmp/spot | egrep -i "<|>|diff" | egrep -i -v "DECLARE|MODIF" 
diff log/tostuff.in log/tostuff.out
