#!/bin/sh
# ============================================================================
# test ups compile 
# ============================================================================
PRODUCTS="$UPS_DIR/test/scripts/compile/db1"; export PRODUCTS
cd $UPS_DIR/test/scripts/compile/log
UPS_SHELL=sh
export UPS_SHELL
$UPS_DIR/test/ups_test << EOD
#
#
configure rover v1_0
upsact_process_commands -out rover1.out -diff rover1.in setup rover v1_0 
#
quit
EOD
UPS_SHELL=csh
$UPS_DIR/test/ups_test << EOD2
#
#
configure rover v1_0
upsact_process_commands -out rover2.out -diff rover2.in setup rover v1_0 
#
quit
EOD2
diff rover.out.sh rover.in.sh
diff rover.out.csh rover.in.csh
