#!/bin/sh
# ============================================================================
# test the file routines
# ============================================================================
cd $UPS_DIR/test/scripts/file
touch dummy.file
$UPS_DIR/test/ups_test << EOD
#ups_echo "================================================================="
upsfil_read_file dog_v2_0.version
upsfil_write_file dog_v2_0.version.out
upsfil_read_file dog_v2_0_1.table
upsfil_write_file dog_v2_0_1.table.out
upsfil_read_file dog_v2_0_1.table2
upsfil_write_file dog_v2_0_1.table2.out
upsfil_write_file -status UPS_OPEN_FILE /junk/junk/junk
upserr_clear
upsfil_read_file -status UPS_NO_FILE blah
upserr_clear
upsfil_read_file -status UPS_READ_FILE dummy.file
upserr_clear
upsfil_read_file -status UPS_SUCCESS invalidkey.version
upserr_clear
upsfil_read_file allkey.version
upserr_clear
quit
EOD
diff dog_v2_0.version dog_v2_0.version.out
diff dog_v2_0_1.table dog_v2_0_1.table.out
diff dog_v2_0_1.table2.out dog_v2_0_1.table.out
rm dummy.file
