#!/bin/sh
# ============================================================================
# test ups stop
# ============================================================================
cd $UPS_DIR/test/scripts/stop/log
SHELL=sh;export SHELL;
UPS_SHELL=${SHELL};export UPS_SHELL;
env PRODUCTS=../db1 $UPS_DIR/test/ups_test << EOD
stop penguin -g current -M ../db1/penguin -m penguin.table -z ../db1 -actout tmp1.out -out penguin1.out -diff penguin1.in
stop penguin v2_0 -q ralph -r ../db1 -actout tmp2.out -out penguin2.out -diff penguin2.in
stop penguin v2_0 -q ralph -z ../db1 -actout tmp3.out -out penguin3.out -diff penguin3.in
stop penguin v2_0 -q ralph -s -n
stop penguin v2_0 -q ralph -s -o
stop penguin v2_0 -q ralph -s -t
stop penguin v2_0 -q ralph -s -V -U /NULL/blah
stop kerplop -status UPS_SUCCESS
quit
EOD
