#!/bin/sh
#
#============================================================================
# test ups configure
#   
#============================================================================
cd $UPS_DIR/test/scripts/configure/log
SHELL=sh;export SHELL;
UPS_SHELL=${SHELL};export UPS_SHELL;
env PRODUCTS=../db $UPS_DIR/test/ups_test << EOD
#ups_echo
#"================================================================="
#
configure baritone -f NULL db -s -o
configure baritone v1_0 -r db -s -n
configure baritone -O db -s -c
configure baritone v1_0 -s -t
#
#
configure trombone v1_0 -g temp -s -actout music -f PLUM -q "music" -V
configure trombone v2_0 -m trombone.table -M "../db/trombone"
configure trombone -f NULL -U $UPS_DIR -z $PRODUCTS -H OSF1
configure trombone v2_0 -actout temp2 -out trombone.out -diff trombone.in
quit
EOD

