---
    release: fddaq-develop

    type: fddaq

    base_release: coredaq-develop

    fddaq:
        - name: cibmodules
          version: "develop"
          commit: null
        - name: ctbmodules
          version: "develop"
          commit: null
        - name: daqsystemtest
          version: "develop"
          commit: null
        - name: dpdklibs
          version: "develop"
          commit: null
        - name: asiolibs
          version: "develop"
          commit: null
        - name: fddetdataformats
          version: "develop"
          commit: null
        - name: fdreadoutlibs
          version: "develop"
          commit: null
        - name: fdreadoutmodules
          version: "develop"
          commit: null
        - name: flxlibs
          version: "develop"
          commit: null
        - name: hermesmodules
          version: "develop"
          commit: null
        - name: rawdatautils
          version: "develop"
          commit: null
        - name: snbmodules
          version: "develop"
          commit: null
        - name: sspmodules
          version: "develop"
          commit: null
        - name: daphnemodules
          version: "develop"
          commit: null
        - name: tdemodules
          version: "develop"
          commit: null
        - name: tpglibs
          version: "develop"
          commit: null
        - name: uhallibs
          version: "develop"
          commit: null
        - name: wibmod
          version: "develop"
          commit: null
        - name: crtmodules
          version: "develop"
          commit: null


    pymodules:
        - name: pip
          version: 25.3
          source:  pypi
        - name: aiohappyeyeballs
          version: 2.6.1
          source:  pypi
        - name: aiohttp
          version: 3.13.3
          source:  pypi
        - name: aiohttp-jinja2
          version: 1.6
          source:  pypi
        - name: aiosignal
          version: 1.4.0
          source:  pypi
        - name: aniso8601
          version: 10.0.1
          source:  pypi
        - name: anyio
          version: 4.12.1
          source:  pypi
        - name: asttokens
          version: 3.0.1
          source:  pypi
        - name: attrs
          version: 25.4.0
          source:  pypi
        - name: bcrypt
          version: 5.0.0
          source:  pypi
        - name: blinker
          version: 1.9.0
          source:  pypi
        - name: cachelib
          version: 0.13.0
          source:  pypi
        - name: certifi
          version: 2026.1.4
          source:  pypi
        - name: cffi
          version: 2.0.0
          source:  pypi
        - name: charset-normalizer
          version: 3.4.4
          source:  pypi
        - name: click
          version: 8.3.1
          source:  pypi
        - name: click-didyoumean
          version: 0.3.1
          source:  pypi
        - name: click-shell
          version: 2.1
          source:  pypi
        - name: colorama
          version: 0.4.6
          source:  pypi
        - name: connectivityserver
          version: develop
          source:  github_DUNE-DAQ
        - name: contourpy
          version: 1.3.3
          source:  pypi
        - name: cryptography
          version: 46.0.3
          source:  pypi
        - name: cycler
          version: 0.12.1
          source:  pypi
        - name: daq-assettools
          version: develop
          source:  github_DUNE-DAQ
        - name: daqpytools
          version: develop
          source:  github_DUNE-DAQ
        - name: decorator
          version: 5.2.1
          source:  pypi
        - name: docopt
          version: 0.6.2
          source:  pypi
        - name: drunc
          version: develop
          source:  github_DUNE-DAQ
        - name: druncschema
          version: develop
          source:  github_DUNE-DAQ
        - name: elisa_client_api
          version: develop
          source:  github_DUNE-DAQ
        - name: executing
          version: 2.2.1
          source:  pypi
        - name: flask
          version: 3.1.2
          source:  pypi
        - name: flask-caching
          version: 2.3.1
          source:  pypi
        - name: flask-httpauth
          version: 4.8.0
          source:  pypi
        - name: flask-restful
          version: 0.3.10
          source:  pypi
        - name: flask-sqlalchemy
          version: 3.1.1
          source:  pypi
        - name: fonttools
          version: 4.61.1
          source:  pypi
        - name: frozenlist
          version: 1.8.0
          source:  pypi
        - name: gevent
          version: 25.9.1
          source:  pypi
        - name: gitdb
          version: 4.0.12
          source:  pypi
        - name: gitpython
          version: 3.1.46
          source:  pypi
        - name: google-auth
          version: 2.47.0
          source:  pypi
        - name: googleapis-common-protos
          version: 1.70.0
          source:  pypi
        - name: greenlet
          version: 3.3.0
          source:  pypi
        - name: grpcio
          version: 1.75.0
          source:  pypi
        - name: grpcio-status
          version: 1.75.0
          source:  pypi
        - name: grpcio-tools
          version: 1.75.0
          source:  pypi
        - name: gunicorn
          version: 23.0.0
          source:  pypi
        - name: h11
          version: 0.16.0
          source:  pypi
        - name: h5py
          version: 3.15.1
          source:  pypi
        - name: httpcore
          version: 1.0.9
          source:  pypi
        - name: httpx
          version: 0.28.1
          source:  pypi
        - name: idna
          version: 3.11
          source:  pypi
        - name: iniconfig
          version: 2.3.0
          source:  pypi
        - name: integrationtest
          version: develop
          source:  github_DUNE-DAQ
        - name: invoke
          version: 2.2.1
          source:  pypi
        - name: ipython
          version: 9.9.0
          source:  pypi
        - name: ipython-pygments-lexers
          version: 1.1.1
          source:  pypi
        - name: itsdangerous
          version: 2.2.0
          source:  pypi
        - name: jedi
          version: 0.19.2
          source:  pypi
        - name: jinja2
          version: 3.1.6
          source:  pypi
        - name: kafka-python
          version: 2.3.0
          source:  pypi
        - name: kiwisolver
          version: 1.4.9
          source:  pypi
        - name: kubernetes
          version: 34.1.0
          source:  pypi
        - name: linkify-it-py
          version: 2.0.3
          source:  pypi
        - name: lxml
          version: 6.0.2
          source:  pypi
        - name: markdown-it-py
          version: 4.0.0
          source:  pypi
        - name: markupsafe
          version: 3.0.3
          source:  pypi
        - name: matplotlib
          version: 3.10.8
          source:  pypi
        - name: matplotlib-inline
          version: 0.2.1
          source:  pypi
        - name: mdit-py-plugins
          version: 0.5.0
          source:  pypi
        - name: mdurl
          version: 0.1.2
          source:  pypi
        - name: msgpack
          version: 1.1.2
          source:  pypi
        - name: multidict
          version: 6.7.0
          source:  pypi
        - name: nest-asyncio
          version: 1.6.0
          source:  pypi
        - name: num2words
          version: 0.5.14
          source:  pypi
        - name: numpy
          version: 2.4.0
          source:  pypi
        - name: oauthlib
          version: 3.3.1
          source:  pypi
        - name: packaging
          version: 25.0
          source:  pypi
        - name: pandas
          version: 2.3.3
          source:  pypi
        - name: paramiko
          version: 4.0.0
          source:  pypi
        - name: parso
          version: 0.8.5
          source:  pypi
        - name: pexpect
          version: 4.9.0
          source:  pypi
        - name: pillow
          version: 12.1.0
          source:  pypi
        - name: platformdirs
          version: 4.5.1
          source:  pypi
        - name: pluggy
          version: 1.6.0
          source:  pypi
        - name: prompt-toolkit
          version: 3.0.52
          source:  pypi
        - name: propcache
          version: 0.4.1
          source:  pypi
        - name: protobuf
          version: 6.33.2
          source:  pypi
        - name: psutil
          version: 7.2.1
          source:  pypi
        - name: ptyprocess
          version: 0.7.0
          source:  pypi
        - name: pure-eval
          version: 0.2.3
          source:  pypi
        - name: pyasn1
          version: 0.6.1
          source:  pypi
        - name: pyasn1-modules
          version: 0.4.2
          source:  pypi
        - name: pycparser
          version: 2.23
          source:  pypi
        - name: pygments
          version: 2.19.2
          source:  pypi
        - name: pynacl
          version: 1.6.2
          source:  pypi
        - name: pyparsing
          version: 3.3.1
          source:  pypi
        - name: pysocks
          version: 1.7.1
          source:  pypi
        - name: pytest
          version: 9.0.2
          source:  pypi
        - name: python-dateutil
          version: 2.9.0.post0
          source:  pypi
        - name: python-ipmi
          version: 0.5.8
          source:  pypi
        - name: pytz
          version: 2025.2
          source:  pypi
        - name: pyyaml
          version: 6.0.3
          source:  pypi
        - name: requests
          version: 2.32.5
          source:  pypi
        - name: requests-oauthlib
          version: 2.0.0
          source:  pypi
        - name: rich
          version: 14.2.0
          source:  pypi
        - name: rsa
          version: 4.9.1
          source:  pypi
        - name: runconftools
          version: develop
          source:  github_DUNE-DAQ
        - name: runconf-ui
          version: develop
          source:  github_DUNE-DAQ
        - name: setuptools
          version: 80.9.0
          source:  pypi
        - name: sh
          version: 2.2.2
          source:  pypi
        - name: six
          version: 1.17.0
          source:  pypi
        - name: smmap
          version: 5.0.2
          source:  pypi
        - name: sqlalchemy
          version: 2.0.45
          source:  pypi
        - name: stack-data
          version: 0.6.3
          source:  pypi
        - name: textual
          version: 7.0.2
          source:  pypi
        - name: textual-dev
          version: 1.8.0
          source:  pypi
        - name: textual-serve
          version: 1.1.3
          source:  pypi
        - name: tqdm
          version: 4.67.1
          source:  pypi
        - name: traitlets
          version: 5.14.3
          source:  pypi
        - name: types-grpcio
          version: 1.0.0.20251009
          source:  pypi
        - name: types-protobuf
          version: 6.32.1.20251210
          source:  pypi
        - name: typing-extensions
          version: 4.15.0
          source:  pypi
        - name: tzdata
          version: 2025.3
          source:  pypi
        - name: uc-micro-py
          version: 1.0.3
          source:  pypi
        - name: urllib3
          version: 2.3.0
          source:  pypi
        - name: wcwidth
          version: 0.2.14
          source:  pypi
        - name: websocket-client
          version: 1.9.0
          source:  pypi
        - name: werkzeug
          version: 3.1.5
          source:  pypi
        - name: yarl
          version: 1.22.0
          source:  pypi
        - name: zope-event
          version: 6.1
          source:  pypi
        - name: zope-interface
          version: 8.2
          source:  pypi
