---
    release: coredaq-develop

    type: coredaq

    externals:
        - name: boost
          version: 1.77.0
          variant: "+context+container cxxstd=2a"
        - name: trace
          version: 3.17.13
          variant: ~
        - name: nlohmann-json
          version: 3.9.0
          variant: ~
        - name: highfive
          version: 2.7.1
          variant: "+mpi"
        - name: hdf5
          version: 1.12.0
          variant: "+mpi+threadsafe"
        - name: py-pybind11
          version: 2.6.2
          variant: ~
        - name: protobuf
          version: 4.24.4
          variant: ~
        - name: krb5
          version: 1.19.2
          variant: ~
        - name: fmt
          version: 8.1.1
          variant: "cxxstd=17 shared=True"
        - name: py-moo
          version: 0.6.7
          variant: ~
        - name: py-anyconfig
          version: 0.9.11
          variant: ~
        - name: py-jsonnet
          version: 0.16.0
          variant: ~
        - name: py-fastjsonschema
          version: 2.14.5
          variant: ~

    devtools:
        - name: cmake
          version: 3.26.3
          variant: ~
        - name: gdb
          version: 13.1 
          variant: "~python"
        - name: ninja
          version: 1.10.0
          variant: ~

    systems:
        - name: python
          version: 3.10.4
          variant: ~
        - name: gcc
          version: 12.1.0
          variant: "+binutils"
        - name: openssh
          version: 8.7p1
          variant: ~

    coredaq:
        - name: daq-cmake
          version: v2.8.0
          commit: null
        - name: daqdataformats
          version: "develop"
          commit: null
        - name: detchannelmaps
          version: "develop"
          commit: null
        - name: detdataformats
          version: "develop"
          commit: null
        - name: ers
          version: "develop"
          commit: null
        - name: hdf5libs
          version: "develop"
          commit: null
        - name: logging
          version: "develop"
          commit: null
        - name: trgdataformats
          version: "develop"
          commit: null

    # others:
    #     - name: daq-release
    #       version: "develop"
    #       commit: null
    #     - name: daq-buildtools
    #       version: "develop"
    #       commit: null
    #     - name: daqsystemtest
    #       version: "develop"
    #       commit: null
    #     - name: pocket
    #       version: "develop"
    #       commit: null
    #     - name: microservices
    #       version: "develop"
    #       commit: null
    #     - name: dqm-backend
    #       version: "develop"
    #       commit: null
    #     - name: grafana-dashboards
    #       version: "develop"
    #       commit: null
