#!/bin/sh

REPO=dunedaq.opensciencegrid.org
DIRFILE=/cvmfs/$REPO/.cvmfsdirtab
cvmfs_server transaction $REPO
if [ -r $DIRFILE ]; then mv $DIRFILE $DIRFILE.old; fi
echo '/products/*/*
/releases/*/*
/pypi-repo
! *.version' >$DIRFILE
echo
echo Publishing changes...
cvmfs_server publish $REPO
