#!/bin/bash

# Split the DUNE file system.
#
# See
#   http://cernvm.cern.ch/portal/filesystem/maintain-repositories
# and
#   https://cdcvs.fnal.gov/redmine/issues/18508

# source repo.sh to get cvmfs repo name
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
source $SCRIPT_DIR/repo.sh

FILES=$*
cvmfs_server transaction $REPO
for FILE in $FILES; do
  DIRFILE=/cvmfs/$REPO/$FILE
  echo Removing $DIRFILE
  rm $DIRFILE
done
echo
echo Publishing changes...
cvmfs_server publish $REPO
