#!/bin/sh

REPO=dunedaq-development.opensciencegrid.org
DIRFILE=/cvmfs/$REPO/.cvmfsdirtab
cvmfs_server transaction $REPO
if [ -r $DIRFILE ]; then mv $DIRFILE $DIRFILE.old; fi
echo '/products/*/*
/sandbox/products_centos8/*/*
/nightly
! *.version' >$DIRFILE
echo
echo Publishing changes...
cvmfs_server publish $REPO
