---
    release: dunedaq-v4.1.0

    type: dunedaq

    externals:
        - name: boost
          version: 1.77.0
          variant: "+context+container cxxstd=2a"
        - name: cetlib
          version: 3.15.00
          variant: ~
        - name: trace
          version: 3.17.09
          variant: ~
        - name: nlohmann-json
          version: 3.9.0
          variant: ~
        - name: pistache
          version: dunedaq-v2.8.0
          variant: ~
        - name: highfive
          version: 2.4.1
          variant: "~mpi  ^hdf5@1.12.0~mpi+threadsafe"
        - name: hdf5
          version: 1.12.0
          variant: "~mpi +threadsafe"
        - name: libzmq
          version: 4.3.4
          variant: ~
        - name: cppzmq
          version: 4.8.1
          variant: ~
        - name: msgpack-c
          version: 3.3.0
          variant: ~
        - name: py-pybind11
          version: 2.6.2
          variant: ~
        - name: uhal
          version: 2.8.1
          variant: ~
        - name: cpr
          version: 1.5.2
          variant: ~
        - name: librdkafka
          version: 1.7.0
          variant: ~
        - name: protobuf
          version: 3.14.0
          variant: ~
        - name: folly
          version: 2021.12.13.00
          variant: "cxxstd=2a"
        - name: felix-software
          version: dunedaq-v2.10.0
          variant: ~
        - name: fftw
          version: 3.3.10
          variant: "~mpi"
        - name: cli11
          version: 2.1.2
          variant: ~
        - name: krb5
          version: 1.19.2
          variant: ~
        - name: intel-tbb
          version: 2020.3
          variant: ~
        - name: dpdk
          version: 22.03.1
          variant: ~
        - name: fmt
          version: 8.1.1
          variant: "cxxstd=17 shared=True"
        - name: py-moo
          version: 0.6.3
          variant: ~
        - name: py-anyconfig
          version: 0.9.11
          variant: ~
        - name: py-jsonnet
          version: 0.16.0
          variant: ~
        - name: py-fastjsonschema
          version: 2.14.5
          variant: ~

    devtools:
        - name: cmake
          version: 3.23.1
          variant: ~
        - name: gdb
          version: 9.2
          variant: "~python"
        - name: ninja
          version: 1.10.0
          variant: ~

    systems:
        - name: python
          version: 3.10.4
          variant: ~
        - name: gcc
          version: 12.1.0
          variant: "+binutils"
        - name: openssh
          version: 8.7p1
          variant: ~

    dunedaq:
        - name: daq-cmake
          version: v2.3.3
          commit: null
        - name: ers
          version: v1.3.0
          commit: null
        - name: logging
          version: v1.0.8
          commit: null
        - name: cmdlib
          version: v1.1.7
          commit: null
        - name: restcmd
          version: v1.2.1
          commit: null
        - name: opmonlib
          version: v1.3.6
          commit: null
        - name: rcif
          version: v1.2.3
          commit: null
        - name: appfwk
          version: v2.8.0
          commit: null
        - name: listrev
          version: v3.3.0
          commit: null
        - name: utilities
          version: v2.3.0
          commit: null
        - name: erskafka
          version: v1.5.0
          commit: null
        - name: kafkaopmon
          version: v1.5.0
          commit: null
        - name: ipm
          version: v2.6.1
          commit: null
        - name: serialization
          version: v1.3.1
          commit: null
        - name: iomanager
          version: v1.3.0
          commit: null
        - name: dfmessages
          version: v2.7.0
          commit: null
        - name: detdataformats
          version: v4.0.0
          commit: null
        - name: trgdataformats
          version: v1.0.1
          commit: null
        - name: detchannelmaps
          version: v1.4.1
          commit: null
        - name: daqdataformats
          version: v3.5.1
          commit: null
        - name: readoutlibs
          version: v1.5.0
          commit: null
        - name: readoutmodules
          version: v1.4.0
          commit: null
        - name: dfmodules
          version: v2.11.0
          commit: null
        - name: timing
          version: v7.3.0
          commit: null
        - name: timinglibs
          version: v2.3.0
          commit: null
        - name: daqconf
          version: v6.0.0
          commit: null
        - name: trigger
          version: v1.5.7
          commit: null
        - name: triggeralgs
          version: v1.1.9
          commit: null
        - name: hdf5libs
          version: v2.5.0
          commit: null
        - name: okssystem
          version: v1.0.0
          commit: null
        - name: oksdbinterfaces
          version: v1.0.0
          commit: null
        - name: oks
          version: v1.0.0
          commit: null
        - name: genconfig
          version: v1.0.0
          commit: null
        - name: oksutils
          version: v1.0.0
          commit: null
        - name: dal
          version: v1.0.0
          commit: null
        - name: coredal
          version: v1.0.0
          commit: null
        - name: oksconfig
          version: v1.0.0
          commit: null
        - name: dbe
          version: v1.0.0
          commit: null

    others:
        - name: daq-release
          version: "develop"
          commit: null
        - name: daq-buildtools
          version: v7.2.1
          commit: null
        - name: daq-systemtest
          version: v2.0.0
          commit: null
        - name: pocket
          version: v0.6.0
          commit: null
        - name: microservices
          version: v1.5.0
          commit: null
        - name: dqm-backend
          version: "develop"
          commit: null
        - name: grafana-dashboards
          version: v1.7.0
          commit: null
