---
    release: coredaq-v5.4.1

    type: coredaq

    externals:
        - name: boost
          version: 1.85.0
          variant: "cxxstd=2a"
        - name: cetlib
          version: 3.18.01
          variant: "+lite"
        - name: trace
          version: 3.17.14
          variant: ~
        - name: nlohmann-json
          version: 3.11.2
          variant: ~
        - name: pistache
          version: fddaq-v5.3.0
          variant: ~
        - name: highfive
          version: 2.9.0
          variant: "+mpi"
        - name: hdf5
          version: 1.14.3
          variant: "+mpi+threadsafe"
        - name: libarchive
          version: 3.7.1
          variant: "crypto=systemssl"
        - name: libzmq
          version: 4.3.5
          variant: ~
        - name: cppzmq
          version: 4.10.0
          variant: ~
        - name: msgpack-c
          version: 3.3.0
          variant: ~
        - name: py-pybind11
          version: 2.12.0
          variant: ~
        - name: uhal
          version: 2.8.1
          variant: ~
        - name: librdkafka
          version: 2.2.0
          variant: ~
        - name: protobuf
          version: 4.24.4
          variant: ~
        - name: grpc
          version: 1.65.1
          variant: "cxxstd=17"
        - name: felix-software
          version: fddaq-v5.3.0
          variant: ~
        - name: folly
          version: 2024.12.02.00
          variant: "cxxstd=2a"
        - name: cli11
          version: 2.3.2
          variant: ~
        - name: intel-tbb
          version: 2021.9.0
          variant: ~
        - name: dpdk
          version: 22.11
          variant: ~
        - name: fmt
          version: 8.1.1
          variant: "cxxstd=17 shared=True"
        - name: py-moo
          version: 0.6.7
          variant: ~
        - name: py-anyconfig
          version: 0.9.11
          variant: ~
        - name: py-jsonnet
          version: 0.16.0
          variant: ~
        - name: rclone
          version: 1.64.0
          variant: ~
        - name: libtorrent
          version: 2.0.9
          variant: ~
        - name: cyrus-sasl
          version: 2.1.28
          variant: ~
        - name: libevent
          version: 2.1.12
          variant: "~openssl"

    devtools:
        - name: cmake
          version: 3.26.3
          variant: "~ownlibs"
        - name: gdb
          version: 14.1 
          variant: "~python"
        - name: ninja
          version: 1.10.0
          variant: ~

    systems:
        - name: python
          version: 3.10.10
          variant: "~ssl"
        - name: gcc
          version: 13.2.0
          variant: "+binutils"

    coredaq:
        - name: daq-cmake
          version: v3.1.1
          commit: null
        - name: ers
          version: v1.5.3
          commit: null
        - name: logging
          version: v2.0.1
          commit: null
        - name: cmdlib
          version: v1.3.0
          commit: null
        - name: restcmd
          version: v1.4.0
          commit: null
        - name: opmonlib
          version: v2.1.3
          commit: null
        - name: rcif
          version: v1.4.0
          commit: null
        - name: appfwk
          version: v5.0.0
          commit: null
        - name: listrev
          version: v6.0.0
          commit: null
        - name: utilities
          version: v4.0.0
          commit: null
        - name: erskafka
          version: v2.1.1
          commit: null
        - name: kafkaopmon
          version: v3.1.1
          commit: null
        - name: ipm
          version: v3.0.0
          commit: null
        - name: serialization
          version: v2.1.0
          commit: null
        - name: iomanager
          version: v3.0.0
          commit: null
        - name: dfmessages
          version: v2.11.0
          commit: null
        - name: detdataformats
          version: v4.2.0
          commit: null
        - name: trgdataformats
          version: v2.0.1
          commit: null
        - name: detchannelmaps
          version: v1.10.0
          commit: null
        - name: daqdataformats
          version: v3.10.1
          commit: null
        - name: datahandlinglibs
          version: v3.1.7
          commit: null
        - name: dfmodules
          version: v5.1.0
          commit: null
        - name: hsilibs
          version: v4.9.0
          commit: null
        - name: timing
          version: v7.11.1
          commit: null
        - name: timinglibs
          version: v4.5.0
          commit: null
        - name: trigger
          version: v2.5.1
          commit: null
        - name: triggeralgs
          version: v1.5.1
          commit: null
        - name: trgtools
          version: v2.2.2
          commit: null
        - name: hdf5libs
          version: v3.3.2
          commit: null
        - name: oks
          version: v1.3.2
          commit: null
        - name: okssystem
          version: v1.0.0
          commit: null
        - name: oksutils
          version: v1.0.0
          commit: null
        - name: oksconflibs
          version: v1.2.0
          commit: null
        - name: conffwk
          version: v2.1.0
          commit: null
        - name: oksdalgen
          version: v1.3.1
          commit: null
        - name: confmodel
          version: v2.5.1
          commit: null
        - name: appmodel
          version: v3.9.0
          commit: null
        - name: dbe
          version: v1.6.1
          commit: null
        - name: daqconf
          version: v8.6.3
          commit: null

    others:
        - name: daq-release
          version: v3.1.1
          commit: null
        - name: daq-buildtools
          version: v8.9.7
          commit: null
        - name: daqsystemtest
          version: v4.5.0
          commit: null
        - name: microservices
          version: v3.1.0
          commit: null
        - name: grafana-dashboards
          version: "develop"
          commit: null
