dune_externals=(
  "boost             v1_73_0         e19:prof"
  "cetlib            v3_11_01        e19:prof"
  "cetlib_except     v1_05_00        e19:prof"
  "cetpkgsupport     v1_14_01                "
  "clang             v7_0_0rc3               "
  "cli11             v2_1_2          e19:prof"
  "cmake             v3_17_2                 "
  "cppunit           v1_15_1a        e19:prof"
  "fmt               v6_2_1          e19:prof"
  "folly             v2021_12_13     e19:prof"
  "double_conversion v3_1_5          e19:prof"
  "gcc               v8_2_0                  "
  "gdb               v9_2                    "
  "glog              v0_4_0          e19:prof"
  "hdf5              v1_12_0a        e19:prof"
  "hep_concurrency   v1_05_00        e19:prof"
  "highfive          v2_3_1          e19:prof"
  "libevent          v2_1_8          e19:prof"
  "ninja             v1_10_0                 "
  "nlohmann_json     v3_9_0c         e19:prof"
  "pistache          v2020_10_07     e19:prof"
  "protobuf          v3_14_0         e19     "
  "python            v3_8_3b                 "
  "sqlite            v3_32_03_00             "
  "tbb               v2020_2a        e19:prof"
  "TRACE             v3_16_02                "
  "fftw              v3_3_10                "
  "zmq               v4_3_1c         e19:prof"
  "cppzmq            v4_3_0          e19:prof"
  "msgpack_c         v3_3_0          e19:prof"
  "felix             v1_2_2          e19:prof"
  "pybind11          v2_6_2          e19:prof"
  "uhal              v2_8_1          e19:prof"
  "cpr               v1_5_2          e19:prof"
  "pugixml           v1_11           e19     "
  "librdkafka        v1_7_0          e19:prof"
  "yaml_cpp          v0_6_3          e19:prof"
  "zstd              v1_5_0          e19:prof"
)

dune_ups=(
  "ups               v6_0_8                  "
)

dune_extras=(
  "daq_buildtools    v4.1.6                  "
  "daq_release       v1.7.7                  "
)

dune_packages=(
  "daq_cmake        v2_1_2d       e19:prof"
  "ers              v1_1_6d       e19:prof"
  "logging          v1_0_5e       e19:prof"
  "cmdlib           v1_1_5e       e19:prof"
  "restcmd          v1_1_5d       e19:prof"
  "opmonlib         v1_3_5        e19:prof"
  "rcif             v1_1_2        e19:prof"
  "appfwk           v2_5_0        e19:prof"
  "listrev          v2_2_2        e19:prof"
  "utilities        v2_0_0        e19:prof"
  "erskafka         v1_4_0d       e19:prof"
  "kafkaopmon       v1_3_2e       e19:prof"
  "influxopmon      v1_5_3e       e19:prof"
  "ipm              v2_4_0        e19:prof"
  "serialization    v1_2_4d       e19:prof"
  "dfmessages       v2_3_0d       e19:prof"
  "detdataformats   v3_3_3b       e19:prof"
  "detchannelmaps   v1_0_3d       e19:prof"
  "daqdataformats   v3_3_3        e19:prof"
  "readoutlibs      v1_0_4        e19:prof"
  "readoutmodules   v1_0_3b       e19:prof"
  "fdreadoutlibs    v1_2_0        e19:prof"
  "ndreadoutlibs    v1_0_2d       e19:prof"
  "dfmodules        v2_6_0        e19:prof"
  "flxlibs          v1_5_0        e19:prof"
  "lbrulibs         v1_1_0        e19:prof"
  "networkmanager   v1_0_4        e19:prof"
  "nwqueueadapters  v1_5_2        e19:prof"
  "timing           v6_1_5        e19:prof"
  "timinglibs       v1_6_4        e19:prof"
  "trigemu          v2_3_2e       e19:prof"
  "daqconf          v5_1_2        e19:prof"
  "trigger          v1_3_7        e19:prof"
  "triggeralgs      v1_1_1        e19:prof"
  "dqm              v1_3_4        e19:prof"
  "hdf5libs         v2_1_0c       e19:prof"
  "rawdatautils     v1_0_0d       e19:prof"
  "uhallibs         v1_1_0        e19:prof"
  "dtpcontrols      v2_0_1        e19:prof"
  "dtpctrllibs      v1_0_0        e19:prof"
  "wibmod           v1_3_2d       e19:prof"
  "sspmodules       v1_0_3d       e19:prof"
)

dune_services=(
  "microservices	v1.0.0"
  "nanorc               v3.2.1"
  "integrationtest      v1.3.2"
  "elisa-client-api     v0.1.0"
  "grafana-dashboards   v1.3.1"
)

dune_pythonmodules=(
  "pip               22.0.4     pypi              " 
  "aniso8601         9.0.1      pypi              "
  "anyconfig         0.9.11     pypi              " 
  "anytree           2.8.0      pypi              " 
  "attrs             20.2.0     pypi              " 
  "bidict            0.21.4     pypi              " 
  "bitarray          2.3.4      pypi              " 
  "certifi           2020.12.5  pypi              " 
  "chardet           3.0.4      pypi              " 
  "click             8.1.2      pypi              " 
  "click-didyoumean  0.3.0      pypi              " 
  "click-shell       2.1        pypi              " 
  "colorama          0.4.4      pypi              " 
  "commonmark        0.9.1      pypi              " 
  "elisa-client-api  0.1.0      github_DUNE-DAQ   " 
  "et-xmlfile        1.0.1      pypi              " 
  "fastjsonschema    2.14.5     pypi              " 
  "Flask             2.1.1      pypi              " 
  "Flask-Cors        3.0.10     pypi              " 
  "Flask-HTTPAuth    4.6.0      pypi              " 
  "Flask-RESTful     0.3.9      pypi              " 
  "future            0.18.2     pypi              " 
  "graphviz          0.16       pypi              " 
  "h5py              3.1.0      pypi              " 
  "idna              2.10       pypi              " 
  "importlib-metadata 4.11.3    pypi              "
  "iniconfig         1.1.1      pypi              " 
  "integrationtest   1.3.2      github_DUNE-DAQ   " 
  "itsdangerous      2.0.1      pypi              " 
  "jdcal             1.4.1      pypi              " 
  "Jinja2            3.1.1      pypi              " 
  "jsonnet           0.16.0     pypi              " 
  "jsonpointer       2.0        pypi              " 
  "jsonschema        3.2.0      pypi              " 
  "MarkupSafe        2.0.1      pypi              " 
  "moo               0.5.7      github_brettviren " 
  "nanorc            3.2.1      github_DUNE-DAQ   " 
  "networkx          2.6.3      pypi              " 
  "numpy             1.21.0     pypi              " 
  "openpyxl          3.0.5      pypi              " 
  "packaging         21.0       pypi              " 
  "pexpect           4.8.0      pypi              " 
  "pluggy            0.13.1     pypi              " 
  "psutil            5.9.0      pypi              "
  "ptyprocess        0.7.0      pypi              " 
  "py                1.10.0     pypi              " 
  "pydot             1.4.2      pypi              " 
  "Pygments          2.10.0     pypi              " 
  "pyparsing         2.4.7      pypi              " 
  "pyrsistent        0.17.3     pypi              " 
  "pytest            6.2.4      pypi              " 
  "python-ipmi       0.5.1      pypi              " 
  "pytz              2022.1     pypi              "
  "pyzmq             22.3.0     pypi              " 
  "requests          2.25.0     pypi              " 
  "rich              10.14.0    pypi              " 
  "sh                1.14.1     pypi              " 
  "six               1.16.0     pypi              " 
  "toml              0.10.2     pypi              " 
  "transitions       0.8.10     pypi              " 
  "urllib3           1.26.5     pypi              " 
  "Werkzeug          2.1.1      pypi              " 
  "zipp              3.8.0      pypi              "
  "zmq               0.0.0      pypi              " 
)
