---
    release: dunedaq-develop

    externals:
        - name: boost
          version: 1.73.0
          variant: "+context+container cxxstd=17"
        - name: cetlib
          version: 3.13.04
          variant: ~
        - name: trace
          version: 3.16.02
          variant: ~
        - name: nlohmann-json
          version: 3.9.0
          variant: ~
        - name: pistache
          version: dunedaq-v2.8.0
          variant: ~
        - name: highfive
          version: 2.3.1
          variant: "~mpi"
        - name: libzmq
          version: 4.3.1
          variant: ~
        - name: cppzmq
          version: 4.3.0
          variant: ~
        - name: msgpack-c
          version: 3.3.0
          variant: ~
        - name: py-pybind11
          version: 2.6.2
          variant: ~
        - name: uhal
          version: 2.8.1
          variant: ~
        - name: cpr
          version: 1.5.2
          variant: ~
        - name: librdkafka
          version: 1.7.0
          variant: ~
        - name: protobuf
          version: 3.14.0
          variant: ~
        - name: folly
          version: 2021.12.13.00
          variant: "cxxstd=17"
        - name: felix-software
          version: dunedaq-v2.10.0
          variant: ~
        - name: fftw
          version: 3.3.10
          variant: "~mpi"
        - name: cli11
          version: 2.1.2
          variant: ~
        - name: krb5
          version: 1.19.2
          variant: ~
        - name: py-pyyaml
          version: 5.3.1
          variant: ~

    devtools:
        - name: cmake
          version: 3.21.4
          variant: ~
        - name: gdb
          version: 9.2
          variant: "~python"
        - name: ninja
          version: 1.10.0
          variant: ~

    systems:
        - name: python
          version: 3.8.3
          variant: ~
        - name: gcc
          version: 8.2.0
          variant: "+binutils"

    dunedaq:
        - name: daq-cmake
          version: "dunedaq-develop"
          commit: null
        - name: ers
          version: "dunedaq-develop"
          commit: null
        - name: logging
          version: "dunedaq-develop"
          commit: null
        - name: cmdlib
          version: "dunedaq-develop"
          commit: null
        - name: restcmd
          version: "dunedaq-develop"
          commit: null
        - name: opmonlib
          version: "dunedaq-develop"
          commit: null
        - name: rcif
          version: "dunedaq-develop"
          commit: null
        - name: appfwk
          version: "dunedaq-develop"
          commit: null
        - name: listrev
          version: "dunedaq-develop"
          commit: null
        - name: utilities
          version: "dunedaq-develop"
          commit: null
        - name: erskafka
          version: "dunedaq-develop"
          commit: null
        - name: kafkaopmon
          version: "dunedaq-develop"
          commit: null
        - name: influxopmon
          version: "dunedaq-develop"
          commit: null
        - name: ipm
          version: "dunedaq-develop"
          commit: null
        - name: serialization
          version: "dunedaq-develop"
          commit: null
        - name: dfmessages
          version: "dunedaq-develop"
          commit: null
        - name: detdataformats
          version: "dunedaq-develop"
          commit: null
        - name: detchannelmaps
          version: "dunedaq-develop"
          commit: null
        - name: daqdataformats
          version: "dunedaq-develop"
          commit: null
        - name: readoutlibs
          version: "dunedaq-develop"
          commit: null
        - name: readoutmodules
          version: "dunedaq-develop"
          commit: null
        - name: fdreadoutlibs
          version: "dunedaq-develop"
          commit: null
        - name: ndreadoutlibs
          version: "dunedaq-develop"
          commit: null
        - name: dfmodules
          version: "dunedaq-develop"
          commit: null
        - name: flxlibs
          version: "dunedaq-develop"
          commit: null
        - name: lbrulibs
          version: "dunedaq-develop"
          commit: null
        - name: networkmanager
          version: "dunedaq-develop"
          commit: null
        - name: nwqueueadapters
          version: "dunedaq-develop"
          commit: null
        - name: timing
          version: "dunedaq-develop"
          commit: null
        - name: timinglibs
          version: "dunedaq-develop"
          commit: null
        - name: trigemu
          version: "dunedaq-develop"
          commit: null
        - name: daqconf
          version: "dunedaq-develop"
          commit: null
        - name: trigger
          version: "dunedaq-develop"
          commit: null
        - name: triggeralgs
          version: "dunedaq-develop"
          commit: null
        - name: dqm
          version: "dunedaq-develop"
          commit: null
        - name: hdf5libs
          version: "dunedaq-develop"
          commit: null
        - name: rawdatautils
          version: "dunedaq-develop"
          commit: null
        - name: uhallibs
          version: "dunedaq-develop"
          commit: null
        - name: dtpcontrols
          version: "dunedaq-develop"
          commit: null
        - name: wibmod
          version: "dunedaq-develop"
          commit: null
        - name: sspmodules
          version: "dunedaq-develop"
          commit: null



    # the following section is not used currently
    pymodules:
        - name: pip
          version: 22.0.3
          source: pypi
        - name: nanorc
          version: 3.0.5
          commit: "sds"
          source: github_DUNE-DAQ
        - name: moo
          version: 0.5.7
          source: github_brettviren
