dune_externals=(
  "boost             v1_73_0         e19:prof"
  "cetlib            v3_11_01        e19:prof"
  "cetlib_except     v1_05_00        e19:prof"
  "cetpkgsupport     v1_14_01                "
  "clang             v7_0_0rc3               "
  "cmake             v3_17_2                 "
  "cppunit           v1_15_1a        e19:prof"
  "fmt               v6_2_1          e19:prof"
  "folly             v2020_05_25a    e19:prof"
  "double_conversion v3_1_5          e19:prof"
  "gcc               v8_2_0                  "
  "gdb               v9_2                    "
  "glog              v0_4_0          e19:prof"
  "hdf5              v1_12_0a        e19:prof"
  "hep_concurrency   v1_05_00        e19:prof"
  "highfive          v2_3_1          e19:prof"
  "libevent          v2_1_8          e19:prof"
  "ninja             v1_10_0                 "
  "nlohmann_json     v3_9_0c         e19:prof"
  "pistache          v2020_10_07     e19:prof"
  "protobuf          v3_14_0         e19     "
  "python            v3_8_3b                 "
  "sqlite            v3_32_03_00             "
  "tbb               v2020_2a        e19:prof"
  "TRACE             v3_16_02                "
  "zmq               v4_3_1c         e19:prof"
  "cppzmq            v4_3_0          e19:prof"
  "msgpack_c         v3_3_0          e19:prof"
  "felix             v1_2_0          e19:prof"
  "pybind11          v2_6_2          e19:prof"
  "uhal              v2_8_1          e19:prof"
  "cpr               v1_5_2          e19:prof"
  "pugixml           v1_11           e19     "
  "librdkafka        v1_7_0          e19:prof"
  "yaml_cpp          v0_6_3          e19:prof"
)

dune_ups=(
  "ups               v6_0_8                  "
)

dune_extras=(
  "daq_buildtools    v4_1_0                  "
  "daq_release       develop                  "
)

dune_packages=(
  "daq_cmake         v2.0.1"
  "ers               develop"
  "erses             develop"
  "logging           develop"
  "cmdlib            develop"
  "restcmd           develop"
  "opmonlib          develop"
  "rcif              develop"
  "appfwk            develop"
  "listrev           develop"
  "serialization     develop"
  "flxlibs           develop"
  "daqdataformats    develop"
  "detdataformats    develop"
  "detchannelmaps    develop"
  "dfmessages        develop"
  "dfmodules         develop"
  "trigemu           develop"
  "readout           develop"
  "minidaqapp        develop"
  "ipm               develop"
  "timing            develop"
  "timinglibs        develop"
  "trigger           develop"
  "triggeralgs       develop"
  "influxopmon       develop"
  "nwqueueadapters   develop"
  "erskafka          develop"
  "dqm               develop"
  "lbrulibs          develop"
  "wibmod            develop"
  "sspmodules        develop"
  "hdf5libs          develop"
)

dune_services=(
  "integrationtest      v1.2.0"
  "nanorc               v2.0.5"
  "microservices	v1.0.0"
  "dqmanalysis	        v1.0.0"
  "daqerrordisplay	v1.0.1"
  "dqmplatform	        v1.1.0"
)
