name: Create build area
description: 'Create nightly build area'

inputs:
  tag:
    type: string
    required: true
    description: 'Base tag for build area'
  path:
    type: string
    default: ''
    description: 'Build area path'
  feature_branch:
    type: string
    default: 'develop'
    description: 'Feature branch to be used across all DAQ repos wherever possible.'
outputs:
  nightly_path:
    value: ${{ steps.create_build_area.outputs.BUILD_PATH }}

runs:
  using: "composite"
  steps:
  - name: Checkout daq-release
    uses: actions/checkout@v6
    with:
      path: daq-release-buildarea
  - name: Get release type
    id: release_type
    shell: bash
    run: |
      ARGS=""
      TYPE=""
      if [[ "$TAG" == NFD_* ]]; then
        echo "Inferred nightly release from tag $TAG"
        ARGS="-n nightly"
        TYPE="nightly"
      elif [[ "$TAG" == *rc* ]]; then
        echo "Inferred candidate release from tag $TAG"
        ARGS="-b candidate"
        TYPE="candidate"
      else
        echo "Inferred stable release from $TAG"
        TYPE="stable"
      fi

      echo "ARGS=$ARGS" >> "$GITHUB_OUTPUT"
      echo "TYPE=$TYPE" >> "$GITHUB_OUTPUT"

  - id: create_build_area
    shell: bash
    env:
      TAG: ${{ inputs.tag }}
      BUILD_PATH: ${{ inputs.path || inputs.tag }}
    run: |
      source /cvmfs/dunedaq.opensciencegrid.org/setup_dunedaq.sh
      setup_dbt latest

      BUILD_ARGS=${{ steps.release_type.outputs.ARGS }}

      echo "Will run: dbt-create $BUILD_ARGS $TAG $BUILD_PATH"
      dbt-create "$BUILD_ARGS" $TAG $BUILD_PATH

      [[ -d "$BUILD_PATH" ]] || exit 2

      echo "BUILD_PATH=$BUILD_PATH" >> "$GITHUB_OUTPUT"

  - id: get_release_manifest
    shell: bash
    env:
      RELEASE_TYPE: ${{ steps.release_type.outputs.TYPE }}
      TAG: ${{ inputs.tag }}
      DAQ_RELEASE: 'daq-release-buildarea'
    run: |
      CORE_RELEASE_MANIFEST=""
      TARGET_RELEASE_MANIFEST=""
      if [[ "$RELEASE_TYPE" == "nightly" ]]; then
        CORE_RELEASE_MANIFEST=$DAQ_RELEASE/configs/coredaq/fddaq-develop/release.yaml
        TARGET_RELEASE_MANIFEST=$DAQ_RELEASE/configs/fddaq/fddaq-develop/release.yaml
      else
        VERSION=$(echo "$tag" | cut -d '-' -f 2)
        core_reLEASE_MANIFEST=$DAQ_RELEASE/configs/coredaq/fddaq-coredaq-$VERSION/release.yaml
        TARGET_RELEASE_MANIFEST=$DAQ_RELEASE/configs/coredaq/fddaq-$VERSION/release.yaml
      fi

      echo "CORE_RELEASE_MANIFEST=$CORE_RELEASE_MANIFEST" >> "$GITHUB_OUTPUT"
      echo "TARGET_RELEASE_MANIFEST=$TARGET_RELEASE_MANIFEST" >> "$GITHUB_OUTPUT"

  - id: checkout_packages
    shell: bash
    env:
      BRANCH: ${{ inputs.feature_branch }}
      BUILD_PATH: ${{ inputs.path || inputs.tag }}
    run: |
      $GITHUB_WORKSPACE/daq-release-buildarea/scripts/checkout-daq-package.py \
        -i ${{ steps.get_release_manifest.outputs.CORE_RELEASE_MANIFEST}} \
        -a -o $BUILD_PATH/sourcecode \
        -b $BRANCH --continue-on-error

      $GITHUB_WORKSPACE/daq-release-buildarea/scripts/checkout-daq-package.py \
        -i ${{ steps.get_release_manifest.outputs.TARGET_RELEASE_MANIFEST}} \
        -a -o $BUILD_PATH/sourcecode \
        -b $BRANCH --continue-on-error

  - id: cleanup
    shell: bash
    run: |
      echo "This is where we should remove: daq-release-buildarea"
      #rm -rf daq-release-buildarea