name: Get release type

description: 'Get release type'

inputs:
  TAG:
    description: 'Relese tag'
    type: string
    required: true

outputs:
  type:
    description: 'One of nightly, stable, or candidate'
    value: ${{ steps.get_release_type.outputs.TYPE }}
  dbt_args:
    description: 'Additional args for dbt-build, dbt-setup-release, etc.'
    value: ${{ steps.get_release_type.outputs.DBT_ARGS }}

runs:
  using: "composite"
  steps:
  - name: Get release type
    id: get_release_type
    shell: bash
    run: |
      TAG="${{ inputs.tag }}"
      if [[ "$TAG" =~ ^[A-Z]+_DEV_[0-9]{6}_[A-Za-z0-9]+$ ]]; then
        echo "TYPE=nightly" >> "$GITHUB_OUTPUT"
        echo "DBT_ARGS=-n"  >> "$GITHUB_OUTPUT"
      elif [[ "$TAG" =~ ^[a-z]+-v[0-9]+\.[0-9]+\.[0-9]+-?rc[0-9]+.*$ ]]; then
        echo "TYPE=candidate"        >> "$GITHUB_OUTPUT"
        echo "DBT_ARGS=-b candidate" >> "$GITHUB_OUTPUT"
      elif [[ "$TAG" =~ ^[a-z]+-v[0-9]+\.[0-9]+\.[0-9]+-?[a-z]+[0-9]+$ ]]; then
        echo "TYPE=stable" >> "$GITHUB_OUTPUT"
        echo "DBT_ARGS="   >> "$GITHUB_OUTPUT"
      else
        echo "ERROR: Unrecognized tag format: ${TAG}"; exit 1
      fi
      cat "$GITHUB_OUTPUT"