name: Get release type

description: 'Get release type'

inputs:
  TAG:
    description: 'Release tag'
    type: string
    required: true

outputs:
  type:
    description: 'One of nightly, stable, or candidate'
    value: ${{ steps.get_release_type.outputs.TYPE }}
  dbt_args:
    description: 'Additional args for dbt-build, dbt-setup-release, etc.'
    value: ${{ steps.get_release_type.outputs.DBT_ARGS }}
  fddaq_manifest:
    description: 'Path to far detector release manifest, relative to daq-release root'
    value: ${{ steps.get_release_type.outputs.FDDAQ_MANIFEST }}
  coredaq_manifest:
    description: 'Path to core release manifest, relative to daq-release root'
    value: ${{ steps.get_release_type.outputs.COREDAQ_MANIFEST }}

runs:
  using: "composite"
  steps:
  - name: Get release type
    id: get_release_type
    shell: bash
    run: |
      TAG="${{ inputs.tag }}"

      if [[ "$TAG" =~ ^[A-Z]+_DEV_[0-9]{6}_[A-Za-z0-9]+$ ]]; then
        echo "TYPE=nightly" >> "$GITHUB_OUTPUT"
        echo "DBT_ARGS=-n"  >> "$GITHUB_OUTPUT"

        echo "FDDAQ_MANIFEST=configs/fddaq/fddaq-develop/release.yml" >> "$GITHUB_OUTPUT"
        echo "COREDAQ_MANIFEST=configs/coredaq/fddaq-develop/release.yml" >> "$GITHUB_OUTPUT"

      # Tags containing vX.Y.Z are either candidate or stable
      elif [[ "$TAG" =~ -v([0-9]+)\.([0-9]+)\.[0-9]+- ]]; then
        MAJOR_VERSION="${BASH_REMATCH[1]}"
        MINOR_VERSION="${BASH_REMATCH[2]}"
        if [[ "$TAG" =~ -rc[0-9]+- ]]; then
          echo "TYPE=candidate"        >> "$GITHUB_OUTPUT"
          echo "DBT_ARGS=-b candidate" >> "$GITHUB_OUTPUT"
        else
          echo "TYPE=stable" >> "$GITHUB_OUTPUT"
          echo "DBT_ARGS="   >> "$GITHUB_OUTPUT"
        fi

        # Backwards compatibility with previous manifest file name format
        VERSION_STRING=$(echo "$TAG" | cut -d "-" -f 2)
        if (( MAJOR_VERSION < 5 || (MAJOR_VERSION == 5 && MINOR_VERSION < 6) )); then
          echo "COREDAQ_MANIFEST=configs/coredaq/coredaq-${VERSION_STRING}/release.yml" >> "$GITHUB_OUTPUT"
        else
          echo "COREDAQ_MANIFEST=configs/coredaq/fddaq-coredaq-${VERSION_STRING}/release.yml" >> "$GITHUB_OUTPUT"
        fi

        echo "FDDAQ_MANIFEST=configs/fddaq/fddaq-${VERSION_STRING}/release.yml" >> "$GITHUB_OUTPUT"

      else
        echo "::error::Unrecognized tag format: ${TAG}"; exit 1
      fi

      cat "$GITHUB_OUTPUT"
