---
    release: dunedaq-v3.2.0

    externals:
        - name: boost
          version: 1.77.0
          variant: "+context+container cxxstd=2a"
        - name: cetlib
          version: 3.15.00
          variant: ~
        - name: trace
          version: 3.17.04
          variant: ~
        - name: nlohmann-json
          version: 3.9.0
          variant: ~
        - name: pistache
          version: dunedaq-v2.8.0
          variant: ~
        - name: highfive
          version: 2.4.1
          variant: "~mpi  ^hdf5@1.12.0~mpi"
        - name: hdf5
          version: 1.12.0
          variant: "~mpi"
        - name: libzmq
          version: 4.3.4
          variant: ~
        - name: cppzmq
          version: 4.8.1
          variant: ~
        - name: msgpack-c
          version: 3.3.0
          variant: ~
        - name: py-pybind11
          version: 2.6.2
          variant: ~
        - name: uhal
          version: 2.8.1
          variant: ~
        - name: cpr
          version: 1.5.2
          variant: ~
        - name: librdkafka
          version: 1.7.0
          variant: ~
        - name: protobuf
          version: 3.14.0
          variant: ~
        - name: folly
          version: 2021.12.13.00
          variant: "cxxstd=2a"
        - name: felix-software
          version: dunedaq-v2.10.0
          variant: ~
        - name: fftw
          version: 3.3.10
          variant: "~mpi"
        - name: cli11
          version: 2.1.2
          variant: ~
        - name: krb5
          version: 1.19.2
          variant: ~
        - name: intel-tbb
          version: 2020.3
          variant: ~
        - name: dpdk
          version: 22.03
          variant: ~
        - name: fmt
          version: 8.1.1
          variant: "cxxstd=17 shared=True"

    devtools:
        - name: cmake
          version: 3.23.1
          variant: ~
        - name: gdb
          version: 9.2
          variant: "~python"
        - name: ninja
          version: 1.10.0
          variant: ~

    systems:
        - name: python
          version: 3.10.4
          variant: ~
        - name: gcc
          version: 12.1.0
          variant: "+binutils"
        - name: openssh
          version: 8.7p1
          variant: ~

    dunedaq:
        - name: daq-cmake
          version: "v2.2.0"
          commit: null
        - name: ers
          version: "v1.1.7"
          commit: null
        - name: logging
          version: "v1.0.7"
          commit: null
        - name: cmdlib
          version: "v1.1.6"
          commit: null
        - name: restcmd
          version: "v1.2.0"
          commit: null
        - name: opmonlib
          version: "v1.3.5"
          commit: null
        - name: rcif
          version: "v1.2.3"
          commit: null
        - name: appfwk
          version: "v2.7.1"
          commit: null
        - name: listrev
          version: "v3.2.0"
          commit: null
        - name: utilities
          version: "v2.2.0"
          commit: null
        - name: erskafka
          version: "v1.4.2"
          commit: null
        - name: kafkaopmon
          version: "v1.4.0"
          commit: null
        - name: ipm
          version: "v2.5.1"
          commit: null
        - name: serialization
          version: "v1.3.0"
          commit: null
        - name: iomanager
          version: "v1.1.0"
          commit: null
        - name: dfmessages
          version: "v2.6.0"
          commit: null
        - name: detdataformats
          version: "v3.6.0"
          commit: null
        - name: detchannelmaps
          version: "v1.2.6"
          commit: null
        - name: daqdataformats
          version: "v3.4.0"
          commit: null
        - name: readoutlibs
          version: "v1.3.0"
          commit: null
        - name: hsilibs
          version: "v1.0.0"
          commit: null
        - name: readoutmodules
          version: "v1.3.2"
          commit: null
        - name: fdreadoutlibs
          version: "v1.5.3"
          commit: null
        - name: ndreadoutlibs
          version: "v1.2.0"
          commit: null
        - name: dfmodules
          version: "v2.9.0"
          commit: null
        - name: flxlibs
          version: "v1.7.4"
          commit: null
        - name: lbrulibs
          version: "v1.2.2"
          commit: null
        - name: timing
          version: "v7.1.0"
          commit: null
        - name: timinglibs
          version: "v2.1.0"
          commit: null
        - name: daqconf
          version: "v5.5.0"
          commit: null
        - name: trigger
          version: "v1.5.2"
          commit: null
        - name: triggeralgs
          version: "v1.1.5"
          commit: null
        - name: dqm
          version: "v1.5.0"
          commit: null
        - name: hdf5libs
          version: "v2.3.0"
          commit: null
        - name: rawdatautils
          version: "v1.2.0"
          commit: null
        - name: uhallibs
          version: "v1.2.0"
          commit: null
        - name: dtpcontrols
          version: "v2.2.1"
          commit: null
        - name: wibmod
          version: "v1.4.4"
          commit: null
        - name: sspmodules
          version: "v1.2.0"
          commit: null
        - name: dtpctrllibs
          version: "v1.2.1"
          commit: null
        - name: ctbmodules
          version: "v1.0.0"
          commit: null
        - name: dpdklibs
          version: "v0.0.1"
          commit: null

    pymodules:
        - name: pip
          version: 22.0.4
          source:  pypi
        - name: aniso8601
          version: 9.0.1
          source:  pypi
        - name: anyconfig
          version: 0.9.11
          source:  pypi
        - name: anytree
          version: 2.8.0
          source:  pypi
        - name: attrs
          version: 20.2.0
          source:  pypi
        - name: bidict
          version: 0.21.4
          source:  pypi
        - name: bitarray
          version: 2.3.4
          source:  pypi
        - name: cachetools
          version: 5.1.0
          source:  pypi
        - name: certifi
          version: 2020.12.5
          source:  pypi
        - name: chardet
          version: 3.0.4
          source:  pypi
        - name: click
          version: 8.1.2
          source:  pypi
        - name: click-configfile
          version: 0.2.3
          source:  pypi
        - name: click-didyoumean
          version: 0.3.0
          source:  pypi
        - name: click-shell
          version: 2.1
          source:  pypi
        - name: colorama
          version: 0.4.4
          source:  pypi
        - name: commonmark
          version: 0.9.1
          source:  pypi
        - name: configparser
          version: 5.2.0
          source:  pypi
        - name: docker
          version: 5.0.3
          source:  pypi
        - name: elisa-client-api
          version: 0.1.0
          source:  github_DUNE-DAQ
        - name: et-xmlfile
          version: 1.0.1
          source:  pypi
        - name: fastjsonschema
          version: 2.14.5
          source:  pypi
        - name: Flask
          version: 2.1.1
          source:  pypi
        - name: Flask-Cors
          version: 3.0.10
          source:  pypi
        - name: Flask-HTTPAuth
          version: 4.6.0
          source:  pypi
        - name: Flask-RESTful
          version: 0.3.9
          source:  pypi
        - name: future
          version: 0.18.2
          source:  pypi
        - name: google-auth
          version: 2.6.6
          source:  pypi
        - name: graphviz
          version: 0.16
          source:  pypi
        - name: h5py
          version: 3.1.0
          source:  pypi
        - name: idna
          version: "2.10"
          source:  pypi
        - name: importlib-metadata
          version: 4.11.3
          source:  pypi
        - name: iniconfig
          version: 1.1.1
          source:  pypi
        - name: integrationtest
          version: 1.5.2
          source:  github_DUNE-DAQ
        - name: itsdangerous
          version: 2.0.1
          source:  pypi
        - name: jdcal
          version: 1.4.1
          source:  pypi
        - name: Jinja2
          version: 3.1.1
          source:  pypi
        - name: jsonnet
          version: 0.16.0
          source:  pypi
        - name: jsonpointer
          version: "2.0"
          source:  pypi
        - name: jsonschema
          version: 3.2.0
          source:  pypi
        - name: kubernetes
          version: 23.6.0
          source:  pypi
        - name: MarkupSafe
          version: 2.0.1
          source:  pypi
        - name: moo
          version: 0.6.3
          source:  github_brettviren
        - name: nanorc
          version: 4.1.3
          source:  github_DUNE-DAQ
        - name: networkx
          version: 2.6.3
          source:  pypi
        - name: numpy
          version: 1.21.0
          source:  pypi
        - name: oauthlib
          version: 3.2.0
          source:  pypi
        - name: openpyxl
          version: 3.0.5
          source:  pypi
        - name: packaging
          version: "21.0"
          source:  pypi
        - name: pexpect
          version: 4.8.0
          source:  pypi
        - name: pluggy
          version: 0.13.1
          source:  pypi
        - name: psutil
          version: 5.9.0
          source:  pypi
        - name: ptyprocess
          version: 0.7.0
          source:  pypi
        - name: py
          version: 1.10.0
          source:  pypi
        - name: pyasn1
          version: 0.4.8
          source:  pypi
        - name: pyasn1-modules
          version: 0.2.8
          source:  pypi
        - name: pydot
          version: 1.4.2
          source:  pypi
        - name: Pygments
          version: 2.10.0
          source:  pypi
        - name: pyparsing
          version: 2.4.7
          source:  pypi
        - name: pyrsistent
          version: 0.17.3
          source:  pypi
        - name: PySocks
          version: 1.7.1
          source:  pypi
        - name: pytest
          version: 6.2.4
          source:  pypi
        - name: python-dateutil
          version: 2.8.2
          source:  pypi
        - name: python-ipmi
          version: 0.5.1
          source:  pypi
        - name: pytz
          version: 2022.1
          source:  pypi
        - name: PyYAML
          version: "6.0"
          source:  pypi
        - name: pyzmq
          version: 22.3.0
          source:  pypi
        - name: requests
          version: 2.25.0
          source:  pypi
        - name: requests-oauthlib
          version: 1.3.1
          source:  pypi
        - name: rich
          version: 10.14.0
          source:  pypi
        - name: rsa
          version: 4.8
          source:  pypi
        - name: sh
          version: 1.14.1
          source:  pypi
        - name: six
          version: 1.16.0
          source:  pypi
        - name: toml
          version: 0.10.2
          source:  pypi
        - name: transitions
          version: 0.8.10
          source:  pypi
        - name: urllib3
          version: 1.26.5
          source:  pypi
        - name: websocket-client
          version: 1.3.2
          source:  pypi
        - name: Werkzeug
          version: 2.1.1
          source:  pypi
        - name: zipp
          version: 3.8.0
          source:  pypi
        - name: zmq
          version: 0.0.0
          source:  pypi
