name: Build Doxygen and publish to GitHub pages

on:
  workflow_dispatch

jobs:
  build-doxygen:
    name: build_doxygen
    runs-on: ubuntu-latest
    #container:
    #  image: "ghcr.io/dune-daq/nightly-release-alma9:production_v4"
    defaults:
      run:
        shell: bash

    steps:
    - uses: cvmfs-contrib/github-action-cvmfs@v4
    - name: Set up cvmfs
      run: |
        /cvmfs/dunedaq.opensciencegrid.org/spack/externals/ext-v2.1/spack-0.20.0/opt/spack/linux-almalinux9-x86_64/gcc-12.1.0/gcc-12.1.0-r5tmamjhdsrukrhvq6bkdxbixgewzvll/bin/gcc --version || exit 1
        ldd /cvmfs/dunedaq.opensciencegrid.org/spack/externals/ext-v2.1/spack-0.20.0/opt/spack/linux-almalinux9-x86_64/gcc-12.1.0/gcc-12.1.0-r5tmamjhdsrukrhvq6bkdxbixgewzvll/bin/gcc || exit 1
        export PATH=/cvmfs/dunedaq.opensciencegrid.org/spack/externals/ext-v2.1/spack-0.20.0/opt/spack/linux-almalinux9-x86_64/gcc-12.1.0/gcc-12.1.0-r5tmamjhdsrukrhvq6bkdxbixgewzvll/bin:$PATH || exit 1
        export LD_LIBRARY_PATH=/cvmfs/dunedaq.opensciencegrid.org/spack/externals/ext-v2.1/spack-0.20.0/opt/spack/linux-almalinux9-x86_64/gcc-12.1.0/gcc-12.1.0-r5tmamjhdsrukrhvq6bkdxbixgewzvll/lib64:$LD_LIBRARY_PATH || exit 1
        echo "CVMFS Success!"

    - name: Checkout dunedaqdoxy
      uses: actions/checkout@v2
      with:
        repository: andrewmogan/dunedaqdoxy
        path: dunedaqdoxy

    - name: Create dbt area, checkout packages, and generate Doxyfile
      run: |
        echo "=======CREATE DBT AREA========="
        source /cvmfs/dunedaq.opensciencegrid.org/setup_dunedaq.sh
        setup_dbt latest_v5
        release_name="last_fddaq"
        cd $GITHUB_WORKSPACE
        if [ -d test_doxygen ]; then rm -rf test_doxygen; fi;
        dbt-create -n $release_name test_doxygen
        cd test_doxygen
        . env.sh
        echo "DBT_AREA_ROOT=$(echo $DBT_AREA_ROOT)" >> $GITHUB_ENV
        echo "DBT_AREA_ROOT is $DBT_AREA_ROOT"

        echo "=======CHECKOUT PACKAGES========="
        echo GITHUB_WORKSPACE is $GITHUB_WORKSPACE
        cd $GITHUB_WORKSPACE
        echo "Am currently in $(pwd)"
        cd dunedaqdoxy
        echo "Now in $(pwd) after cd dunedaqdoxy"
        ./checkout-daq-package.py -i ddaq_release.yaml -a -o $DBT_AREA_ROOT/sourcecode

        echo "========DBT-BUILD========="
        cd $DBT_AREA_ROOT
        dbt-workarea-env
        dbt-build --codegen-only

        echo "========GENERATE DOXYFILE========"
        cd $GITHUB_WORKSPACE/dunedaqdoxy
        ./doxygen_gen.py --source_dir $DBT_AREA_ROOT/sourcecode --build_dir $DBT_AREA_ROOT/build
        echo "ls of package oksutils in checkout step: $(ls $GITHUB_WORKSPACE/test_doxygen/sourcecode/oksutils)"
        echo "ls of dunedaqdoxy: $(ls -l $GITHUB_WORKSPACE/dunedaqdoxy)"
        echo "Contents of Doxyfile INPUT:"
        cat $GITHUB_WORKSPACE/dunedaqdoxy/Doxyfile | grep -A 20 INPUT

    - name: Doxygen Action
      uses: mattnotmitt/doxygen-action@v1.1.0
      with:
        working-directory: 'dunedaqdoxy'
        doxyfile-path: 'Doxyfile'

    - name: Print debug
      run: |
        echo "ls of package oksutils in debug step: $(ls $GITHUB_WORKSPACE/test_doxygen/sourcecode/oksutils)"

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: $DBT_AREA_ROOT/docs/html
        enable_jekyll: false
        allow_empty_commit: false
        force_orphan: true
        publish_branch: gh-pages

    - name: Clean up dbt area
      if: always()
      run: |
        echo "Removing contents of $DBT_AREA_ROOT"
        rm -rf $DBT_AREA_ROOT
        echo "Removing $GITHUB_WORKSPACE/dunedaqdoxy"
        rm -rf $GITHUB_WORKSPACE/dunedaqdoxy

