name: Alma9 build v5 nightly release with externals v2.3

on:
  schedule:
    - cron: "0 3 * * *"

  workflow_dispatch:
    inputs:
      tag-prefix:
        description: 'nightly tag prefix (also used for output container tag)'
        default: ''
      feature-branch:
        description: 'feature branch to be used across all DAQ repos wherever possible.'
        default: develop
      cvmfs-deployment:
        description: 'whether to deploy the release to cvmfs'
        default: 'no'
      send-slack-message:
        description: 'whether to send a message to #daq-release-notifications on completion'
        default: 'no'

jobs:
  make_tags:
    name: create base tag and detector tag
    runs-on: ubuntu-latest
    outputs:
      base_tag: ${{ steps.create_tags.outputs.base_tag }} 
      detector_tag: ${{ steps.create_tags.outputs.detector_tag }} 
    defaults:
      run:
        shell: bash
    steps:
    - id: create_tags
      run: |
        date_tag=$(date +%y%m%d)

        # Use GitHub input if provided, else default to N
        prefix="${{ github.event.inputs.tag-prefix }}"
        if [[ -z "$prefix" ]]; then
          prefix="N"
        fi

        base_tag="${prefix}B_DEV_${date_tag}_A9"
        detector_tag="${prefix}FD_DEV_${date_tag}_A9"

        echo "base_tag=$base_tag" >> "$GITHUB_OUTPUT"
        echo "detector_tag=$detector_tag" >> "$GITHUB_OUTPUT"
        echo "detector_tag=$detector_tag" >> "$GITHUB_ENV"
        echo "base_tag=$base_tag"
        echo "detector_tag=$detector_tag"
    #- uses: cvmfs-contrib/github-action-cvmfs@v5
    #  with:
    #    cvmfs_repositories: 'dunedaq-development.opensciencegrid.org'
    #- name: Check tag on cvmfs
    #  run: |
    #    if [[ -d /cvmfs/dunedaq-development.opensciencegrid.org/nightly/${detector_tag} ]]; then
    #      echo "ERROR: Build area $detector_tag already exists on CVMFS."
    #      exit 1
    #    fi

  build_the_develop_release_spack:
    name: build_dev_release_spack
    runs-on: daq
    needs: make_tags
    container:
      image: ghcr.io/dune-daq/alma9-slim-externals:v2.3
    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout daq-release
      uses: actions/checkout@v4
      with:
        path: daq-release
    
    - name: Set environment variables
      run: |
        echo "BASE_RELEASE_DIR=/cvmfs/dunedaq-development.opensciencegrid.org/nightly/${{ needs.make_tags.outputs.base_tag }}" >> $GITHUB_ENV
        echo "DET_RELEASE_DIR=/cvmfs/dunedaq-development.opensciencegrid.org/nightly/${{ needs.make_tags.outputs.detector_tag }}" >> $GITHUB_ENV
        echo "OS=almalinux9" >> $GITHUB_ENV

    - name: setup directories and install spack for the coredaq release
      run: |
        source daq-release/.github/workflows/wf-setup-tools.sh
        input_feature_branch=${{ github.event.inputs.feature-branch }}
        # For automatically triggered workflows where feature-branch is not set, fall back to default branch
        branch=${input_feature_branch:-"develop"}
        daq-release/scripts/checkout-daq-package.py -i daq-release/configs/coredaq/coredaq-develop/release.yaml -a -o $DET_RELEASE_DIR/sourcecode -b $branch --continue-on-error || [[ "$branch" != "develop" ]]
        daq-release/scripts/spack/build-release.sh $BASE_RELEASE_DIR $DET_RELEASE_DIR core $OS ${{ github.event.inputs.feature-branch }}

        cd $BASE_RELEASE_DIR/../
        tar_and_stage_release ${BASE_RELEASE_TAG}

    - name: upload spack nightly tarball for base release
      uses: actions/upload-artifact@v6
      with:
        name: nightly_coredaq
        path: ${{ github.workspace }}/tarballs_for_upload/${{needs.make_tags.outputs.base_tag}}.tar.gz

    - name: setup directories and install spack for the fddaq release
      run: |
        source daq-release/.github/workflows/wf-setup-tools.sh
        input_feature_branch=${{ github.event.inputs.feature-branch }}
        # For automatically triggered workflows where feature-branch is not set, fall back to default branch
        branch=${input_feature_branch:-"develop"}
        daq-release/scripts/checkout-daq-package.py -i daq-release/configs/fddaq/fddaq-develop/release.yaml -a -o $DET_RELEASE_DIR/sourcecode -b $branch --continue-on-error || [[ "$branch" != "develop" ]]
        daq-release/scripts/checkout-daq-package.py -i daq-release/configs/fddaq/fddaq-develop/release.yaml -a -o $DET_RELEASE_DIR/sourcecode -b $branch --pymodules --continue-on-error || [[ "$branch" != "develop" ]]
        daq-release/scripts/spack/build-release.sh $BASE_RELEASE_DIR $DET_RELEASE_DIR fd $OS ${{ github.event.inputs.feature-branch }}

        cd $DET_RELEASE_DIR/../
        tar_and_stage_release ${DET_RELEASE_TAG}

    - name: upload spack nightly tarball for far detector release
      uses: actions/upload-artifact@v6
      with:
        name: nightly_fddaq
        path: ${{ github.workspace }}/tarballs_for_upload/${{needs.make_tags.outputs.detector_tag}}.tar.gz

  update_image:
    name: update_spack_image_nightly
    runs-on: daq
    strategy:
      matrix:
        include:
          - input_image: "ghcr.io/dune-daq/alma9-slim-externals:v2.3"
            output_image: "ghcr.io/dune-daq/nightly-release-alma9"
            tag: "development_v5${{ github.event.inputs.tag-prefix }}"
    needs: [build_the_develop_release_spack, make_tags] 
    environment: dockerhub
    permissions:
      packages: write
      contents: read

    steps:
      - name: clean docker-build
        run: |
            mkdir -p ${GITHUB_WORKSPACE}/docker-build 
            rm -rf ${GITHUB_WORKSPACE}/docker-build/*

      - name: Download spack nightly release tarball artifact for base release
        uses: actions/download-artifact@v7
        with:
          name: nightly_coredaq
          path: ${{ github.workspace }}/docker-build

      - name: Download spack nightly release tarball artifact for far detector release
        uses: actions/download-artifact@v7
        with:
          name: nightly_fddaq
          path: ${{ github.workspace }}/docker-build

      - name: prepare cvmfs mirror spack-nightly
        env:
          BASE_TAG: ${{needs.make_tags.outputs.base_tag}}
          DETECTOR_TAG: ${{needs.make_tags.outputs.detector_tag}}
        run: |
            cd ${{ github.workspace }}/docker-build
            mkdir -p nightly

            cd nightly
            tar xf ../${BASE_TAG}.tar.gz
            rm -rf ../${BASE_TAG}.tar.gz

            tar xf ../${DETECTOR_TAG}.tar.gz
            rm -rf ../${DETECTOR_TAG}.tar.gz

            if [[ "${DETECTOR_TAG}" == NFD_* ]]; then
              ln -s ${DETECTOR_TAG} last_fddaq
            fi

            cd ..
            echo "FROM "${{ matrix.input_image }} > Dockerfile
            echo 'MAINTAINER John Freeman "jcfree@fnal.gov"' >> Dockerfile
            echo "ENV REFRESHED_AT ${BASE_TAG}" >> Dockerfile
            echo "COPY --from=ghcr.io/dune-daq/pypi-repo:latest /cvmfs/dunedaq.opensciencegrid.org/pypi-repo /cvmfs/dunedaq.opensciencegrid.org/pypi-repo" >> Dockerfile
            echo "ADD nightly /cvmfs/dunedaq-development.opensciencegrid.org/nightly" >> Dockerfile
            echo 'ENTRYPOINT ["/bin/bash"]' >> Dockerfile

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/dune-daq/nightly-release-alma9
          tags: |
            type=raw,value=development_v5${{ github.event.inputs.tag-prefix }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v6
        with:
          context: ${{ github.workspace }}/docker-build
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}


  generate_dbt_setup_release_env:
    name: generate_dbt_setup_release_env
    runs-on: daq
    needs: [make_tags, update_image]
    container:
      image: ghcr.io/dune-daq/nightly-release-alma9:development_v5${{ github.event.inputs.tag-prefix }}
    defaults:
      run:
        shell: bash

    steps:
    
    - name: create dbt-setup-release-env.sh and daq_app_rte.sh for fddaq
      env:
          DETECTOR_TAG: ${{needs.make_tags.outputs.detector_tag}}
      run: |
          export DET=fd

          source /cvmfs/dunedaq.opensciencegrid.org/setup_dunedaq.sh
          setup_dbt latest_v5
          dbt-setup-release -n ${DETECTOR_TAG}
          declare -x > ${GITHUB_WORKSPACE}/${DET}daq-dbt-setup-release-env.sh
          declare -f >> ${GITHUB_WORKSPACE}/${DET}daq-dbt-setup-release-env.sh
          egrep "declare -x (PATH|.*_SHARE|CET_PLUGIN_PATH|DUNEDAQ_SHARE_PATH|LD_LIBRARY_PATH|LIBRARY_PATH|PYTHONPATH)=" ${GITHUB_WORKSPACE}/${DET}daq-dbt-setup-release-env.sh > ${GITHUB_WORKSPACE}/${DET}daq_app_rte.sh

    - name: upload fddaq-dbt-setup-release-env.sh
      uses: actions/upload-artifact@v6
      with:
        name: fddaq-dbt_setup_release_env
        path: ${{ github.workspace }}/fddaq-dbt-setup-release-env.sh

    - name: upload fddaq_app_rte.sh
      uses: actions/upload-artifact@v6
      with:
        name: fddaq_app_rte
        path: ${{ github.workspace }}/fddaq_app_rte.sh

  publish_to_cvmfs:
    name: publish to cvmfs
    needs: [generate_dbt_setup_release_env, make_tags]
    runs-on: daq

    steps:
    - name: check_cvmfs_deployment
      id: do_deployment
      run: |
        cvmfs_deployment_input=${{ github.event.inputs.cvmfs-deployment }}
        cvmfs_deployment_flag=${cvmfs_deployment_input:-"yes"}
        echo "Do cvmfs deployment: ${cvmfs_deployment_flag}"
        [[ ${cvmfs_deployment_flag} == 'yes' ]] && exit 0 || exit 1
      continue-on-error: true

    - name: download fddaq-dbt-setup-release-env.sh
      if: steps.do_deployment.outcome == 'success'
      uses: actions/download-artifact@v7
      with:
        name: fddaq-dbt_setup_release_env
        path: ${{ github.workspace }}/fddaq-release

    - name: download fddaq_app_rte.sh
      if: steps.do_deployment.outcome == 'success'
      uses: actions/download-artifact@v7
      with:
        name: fddaq_app_rte
        path: ${{ github.workspace }}/fddaq-rte

    - name: start docker container, and then rsync... 
      if: steps.do_deployment.outcome == 'success'
      run: |
        [[ ${DO_DEPLOYMENT} == 'no' ]] && exit 0

        cd $GITHUB_WORKSPACE

        IMAGE="ghcr.io/dune-daq/nightly-release-alma9:development_v5${{ github.event.inputs.tag-prefix }}"
        unique_name=$( date | tr " :" _ )

        docker pull $IMAGE
        files_to_copy=$( docker run --rm --entrypoint ls $IMAGE /cvmfs/dunedaq-development.opensciencegrid.org/nightly )

        docker run --name $unique_name $IMAGE
        mkdir $unique_name

        for file in $files_to_copy; do
             docker cp $unique_name:/cvmfs/dunedaq-development.opensciencegrid.org/nightly/$file $unique_name
        done
        docker rm $unique_name
        docker system prune -f

        #dir_for_env_scripts=$( find $unique_name -mindepth 1 -maxdepth 1 -type d -name "NFD*" )
        dir_for_env_scripts="$unique_name/${{ needs.make_tags.outputs.detector_tag }}"
        cp ./fddaq-release/fddaq-dbt-setup-release-env.sh     $dir_for_env_scripts/dbt-setup-release-env.sh
        cp ./fddaq-rte/fddaq_app_rte.sh                       $dir_for_env_scripts/daq_app_rte.sh

        kinit  -k -t $HOME/daq-nightly.keytab nightly-build/dune/daq.dunescience.org@FNAL.GOV

        ssh -o StrictHostKeyChecking=no -l cvmfsdunedaqdev oasiscfs05.fnal.gov "cvmfs_server transaction dunedaq-development.opensciencegrid.org"

        rsync -e "ssh -o StrictHostKeyChecking=no" -rlpt --stats $unique_name/* cvmfsdunedaqdev@oasiscfs05.fnal.gov:/cvmfs/dunedaq-development.opensciencegrid.org/nightly

        ssh -o StrictHostKeyChecking=no -l cvmfsdunedaqdev oasiscfs05.fnal.gov "cvmfs_server publish dunedaq-development.opensciencegrid.org"

        rm -rf $unique_name

  send_slack_message:
    if: (github.event_name != 'workflow_dispatch' && failure()) || (github.event_name == 'workflow_dispatch' && github.event.inputs.send-slack-message == 'yes')
    needs: [make_tags, publish_to_cvmfs]
    uses: ./.github/workflows/slack-notification.yml
    with:
      release_tag: ${{ needs.make_tags.outputs.detector_tag }}
    secrets: 
      #slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
      slack_webhook_url: ${{ secrets.SLACK_TEST_WEBHOOK }}

  poll_cvmfs_for_release:
    needs: [make_tags, publish_to_cvmfs]
    uses: ./.github/workflows/poll-cvmfs-for-release.yml
    with:
      tag-pattern: ${{ needs.make_tags.outputs.detector_tag }}

  cleanup_tarballs:
    name: cleanup tarballs from runner
    runs-on: daq
    if: always()
    needs: publish_to_cvmfs
    steps:
    - name: cleanup tarballs from daq.fnal.gov
      run: |
        files_older_than_30_days=$(find "${{ github.workspace }}/tarballs_for_upload" -name "*.tar.gz" -mtime +30 -print)
        echo "Found the following files older than 30 days:"
        echo "$files_older_than_30_days"
        if [[ -n "$files_older_than_30_days" ]]; then
          echo "Removing $(files_older_than_30_days)"
          rm -f "$files_older_than_30_days"
        fi

