name: Alma9 build v5 nightly release with externals v2.1

on:
  workflow_dispatch

jobs:
  print-statement:
    runs-on: ubuntu-latest
    steps:
      - name: Print to screen
        run: echo "This is a placeholder workflow so I can run a workflow of the same name from a feature branch"

