name: Build Doxygen and publish to GitHub pages

on:
  workflow_dispatch

jobs:
  build-doxygen:
    name: build_doxygen
    runs-on: ubuntu-latest
    container:
      image: "ghcr.io/dune-daq/nightly-release-alma9:development_v5"
    env: 
      DEV_AREA_NAME: 'dev_area'
    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout dunedaqdoxy
      uses: actions/checkout@v2
      with:
        repository: andrewmogan/dunedaqdoxy
        path: dunedaqdoxy

    - name: Checkout daq-release
      uses: actions/checkout@v2
      with:
        path: daq-release

    - name: Create dbt area, checkout packages, and generate Doxyfile
      run: |
        echo "=======CREATE DBT AREA========="
        source /cvmfs/dunedaq.opensciencegrid.org/setup_dunedaq.sh
        setup_dbt latest_v5
        release_name="last_fddaq"
        cd $GITHUB_WORKSPACE
        dbt-create -n $release_name ${{ env.DEV_AREA_NAME }}
        cd ${{ env.DEV_AREA_NAME }}
        . env.sh
        cd sourcecode
        git clone https://github.com/DUNE-DAQ/appfwk.git
        git clone https://github.com/DUNE-DAQ/oksconfgen.git
        echo "DBT_AREA_ROOT=$(echo $DBT_AREA_ROOT)" >> $GITHUB_ENV
        echo "DBT_AREA_ROOT is $DBT_AREA_ROOT"

        #echo "=======CHECKOUT PACKAGES========="
        #echo GITHUB_WORKSPACE is $GITHUB_WORKSPACE
        #cd $GITHUB_WORKSPACE
        #echo "Am currently in $(pwd)"
        #cd dunedaqdoxy
        #echo "Now in $(pwd) after cd dunedaqdoxy"
        # ./checkout-daq-package.py -i $GITHUB_WORKSPACE/daq-release/configs/coredaq/coredaq-develop/release.yaml -a -o $DBT_AREA_ROOT/sourcecode

        echo "========DBT-BUILD========="
        cd $DBT_AREA_ROOT
        dbt-workarea-env
        spack load dbe || true
        spack unload dbe || true
        dbt-build --codegen-only

        echo "========GENERATE DOXYFILE========"
        cd $GITHUB_WORKSPACE/dunedaqdoxy
        ./doxygen_gen.py --source_dir $DBT_AREA_ROOT/sourcecode --build_dir $DBT_AREA_ROOT/build
        # Fix paths in Doxyfile so they can be seen by the Doxygen action container, which uses /github/workspace
        sed -i "s|${DBT_AREA_ROOT}|/github/workspace|g" Doxyfile
        echo "Contents of Doxyfile INPUT:"
        cat $GITHUB_WORKSPACE/dunedaqdoxy/Doxyfile | grep -A 10 "INPUT   "

    - name: Doxygen Action
      uses: mattnotmitt/doxygen-action@v1.1.0
      with:
        #working-directory: 'dunedaqdoxy'
        working-directory: /github/workspace
        doxyfile-path: 'dunedaqdoxy/Doxyfile'

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: $DBT_AREA_ROOT/docs/html
        enable_jekyll: false
        allow_empty_commit: false
        force_orphan: true
        publish_branch: gh-pages

    - name: Clean up dbt area
      if: always()
      run: |
        echo "Removing contents of $DBT_AREA_ROOT"
        rm -rf $DBT_AREA_ROOT
        echo "Removing $GITHUB_WORKSPACE/dunedaqdoxy"
        rm -rf $GITHUB_WORKSPACE/dunedaqdoxy

