name: SL7 build v4 or v5 frozen release 


on:
  workflow_dispatch:
    inputs:
      base-release:
        description: 'targeted base release (e.g. v4.4.0)'
        required: true
      det-release:
        description: 'targeted detector release (e.g. v4.3.0)'
        required: true
      det:
        description: 'detector type (nd or fd)'
        required: true
      build-number:
        description: 'frozen release number, e.g. 1'
        required: true

jobs:
  build_the_frozen_release_spack:
    name: build_frozen_release_spack
    runs-on: daq
    container:
      image: ghcr.io/dune-daq/sl7-slim-externals:v1.1
    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout daq-release
      uses: actions/checkout@v3
      with:
        path: daq-release
