name: Build Doxygen and publish to GitHub pages

on:
  workflow_dispatch

jobs:
  build-doxygen:
    name: build_doxygen
    runs-on: ubuntu-latest
    container:
      image: "ghcr.io/dune-daq/nightly-release-alma9:development_v5"
    env: 
      DEV_AREA_NAME: 'dev_area'
    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout dunedaqdoxy
      uses: actions/checkout@v2
      with:
        repository: andrewmogan/dunedaqdoxy
        path: dunedaqdoxy

    - name: Checkout daq-release
      uses: actions/checkout@v2
      with:
        path: daq-release

    - name: Create dbt area
      run: |
        source /cvmfs/dunedaq.opensciencegrid.org/setup_dunedaq.sh
        setup_dbt latest_v5
        date_tag=$(date +%y%m%d)
        release_name=NFD_DEV_${date_tag}_A9
        cd $GITHUB_WORKSPACE
        dbt-create -n $release_name ${{ env.DEV_AREA_NAME }}
        cd ${{ env.DEV_AREA_NAME }}
        . env.sh
        echo "DBT_AREA_ROOT=$(echo $DBT_AREA_ROOT)" >> $GITHUB_ENV
        echo "DBT_AREA_ROOT is $DBT_AREA_ROOT"

    - name: Checkout packages
      run: |
        cd $GITHUB_WORKSPACE/dunedaqdoxy
        ./checkout-daq-package.py -i $GITHUB_WORKSPACE/daq-release/configs/coredaq/coredaq-develop/release.yaml -a -o $DBT_AREA_ROOT/sourcecode
        # triggeralgs doesn't currently work with --codegen-only build; remove for now
        rm -rf $DBT_AREA_ROOT/sourcecode/triggeralgs

    - name: Build dbt area
      run: |
        cd $DBT_AREA_ROOT
        . env.sh
        spack load dbe || true
        spack unload dbe || true
        dbt-build --codegen-only

    - name: Generate Doxyfile
      run: |
        cd $GITHUB_WORKSPACE/dunedaqdoxy
        # ./doxygen_gen.py --source_dir $DBT_AREA_ROOT/sourcecode --build_dir $DBT_AREA_ROOT/build
        ./doxygen_gen.py
        # Edit paths in Doxyfile so they can be seen by the Doxygen action container, which uses /github/workspace
        export DEV_AREA_NAME=${{ env.DEV_AREA_NAME }}
        sed -i "s|${DBT_AREA_ROOT}|/github/workspace/${{ env.DEV_AREA_NAME }}|g" Doxyfile
        echo "Contents of Doxyfile INPUT:"
        cat $GITHUB_WORKSPACE/dunedaqdoxy/Doxyfile | grep -A 10 "INPUT   "

    - name: Doxygen Action
      uses: mattnotmitt/doxygen-action@v1.9.8
      with:
        #working-directory: 'dunedaqdoxy'
        working-directory: /github/workspace/dunedaqdoxy
        doxyfile-path: './Doxyfile'

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dunedaqdoxy/docs/html
        enable_jekyll: false
        allow_empty_commit: false
        force_orphan: true
        publish_branch: gh-pages

    - name: Clean up dbt area
      if: always()
      run: |
        echo "Removing contents of $DBT_AREA_ROOT"
        rm -rf $DBT_AREA_ROOT
        echo "Removing $GITHUB_WORKSPACE/dunedaqdoxy"
        rm -rf $GITHUB_WORKSPACE/dunedaqdoxy

