name: alma9 build testenv with externals v2.3

on:
  workflow_dispatch:
    inputs:
      tag-prefix:
        description: 'nightly tag prefix (also used for output container tag)'
        default: ''
      feature-branch:
        description: 'feature branch to be used across all DAQ repos wherever possible.'
        default: develop
      cvmfs-deployment:
        description: 'whether to deploy the release to cvmfs'
        default: 'no'
      send-slack-message:
        description: 'whether to send a message to #daq-release-notifications on completion'
        default: 'no'

jobs:
  make_tags:
    name: create core tag and target tag
    runs-on: ubuntu-latest
    outputs:
      core_tag: ${{ steps.create_tags.outputs.core_tag }} 
      target_tag: ${{ steps.create_tags.outputs.target_tag }} 
    defaults:
      run:
        shell: bash
    steps:
    - id: create_tags
      run: |
        date_tag=$(date +%y%m%d)

        # Use GitHub input if provided, else default to N
        prefix="${{ github.event.inputs.tag-prefix }}"
        if [[ -z "$prefix" ]]; then
          prefix="N"
        fi

        core_tag="${prefix}TEB_DEV_${date_tag}_A9"
        target_tag="${prefix}TE_DEV_${date_tag}_A9"

        echo "core_tag=$core_tag" >> "$GITHUB_OUTPUT"
        echo "target_tag=$target_tag" >> "$GITHUB_OUTPUT"
        echo "target_tag=$target_tag" >> "$GITHUB_ENV"
        echo "core_tag=$core_tag"
        echo "target_tag=$target_tag"
