name: Create build area (test)

on:
  workflow_dispatch:
    inputs:
      tag:
        type: string
        required: true
        description: 'Base tag for build area'
      path:
        type: string
        default: ''
        description: 'Build area path'
      feature_branch:
        type: string
        default: 'develop'
        description: 'Feature branch to be used across all DAQ repos wherever possible.'

jobs:
  build_release_area:
    runs-on: daq
    steps:
    #- id: checkout
    #  uses: actions/checkout@v6
    #  with:
    #    path: daq-release-test
    - id: create_nightly_build_area
      uses: ./.github/actions/create-build-area
      with:
        tag: ${{ inputs.tag }}
        feature-branch: ${{ inputs.feature_branch || 'develop' }}
    - id: create_symlink
      run: ln -s ${{ steps.create_nightly_build_area.outputs.NIGHTLY_PATH }} latest_nightly
    #- id: cleanup
    #  run: rm -rf daq-release-test
