name: Extended integration test workflow

permissions:
  contents: read

on:
  schedule:
    - cron: "0 6 * * *"

  workflow_dispatch:
    inputs:
      send-slack-message:
        description: 'whether to send a message to #daq-release-notifications on completion'
        default: 'no'
      release-tag:
        description: >-
          Release to test, e.g., NFD_DEV_YYMMDD_A9, fddaq-vX.Y.Z-a9, etc. 
          Default: last_fddaq (latest nightly)
        required: false
        default: 'last_fddaq'

jobs:
  make_variables:
    name: create nightly tag, timestamp, etc.
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.create_variables.outputs.release_tag }}
      timestamp: ${{ steps.create_variables.outputs.timestamp }}
      persistent_log_dir: ${{ steps.create_variables.outputs.persistent_log_dir }}
      integtest_output_path: ${{ steps.create_variables.outputs.integtest_output_path }}
      daq_release_path: ${{ steps.create_variables.outputs.daq_release_path }}
      dbt_args: ${{ steps.release_type.outputs.dbt_args }}
      coredaq_manifest: ${{ steps.release_type.outputs.coredaq_manifest }}
      fddaq_manifest: ${{ steps.release_type.outputs.fddaq_manifest }}
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v6
      - id: create_variables
        run: |
          tag="${{ inputs.release-tag }}"
          release_tag="${tag:-last_fddaq}"
          if [[ "$release_tag" == "last_fddaq" ]]; then
            release_tag="NFD_DEV_$(date +%y%m%d)_A9"
          fi

          timestamp=$(date +"%Y-%m-%d-%H%M%Z")
          persistent_log_dir=/home/nfs/dunedaq/github-actions/pytest-logs-extended-${timestamp}
          integtest_output_path=/home/nfs/dunedaq/actions-runner/_work/daq-release/daq-release/integration_tests_${release_tag}
          daq_release_path="daq-release-extended-tests"

          echo "release_tag=${release_tag}"  >>  "$GITHUB_OUTPUT"
          echo "timestamp=${timestamp}" >> "$GITHUB_OUTPUT"
          echo "persistent_log_dir=${persistent_log_dir}" >> "$GITHUB_OUTPUT"
          echo "integtest_output_path=${integtest_output_path}" >> "$GITHUB_OUTPUT"
          echo "daq_release_path=${daq_release_path}" >> "$GITHUB_OUTPUT"
          cat "$GITHUB_OUTPUT"
      - name: Get release type
        id: release_type
        uses: ./.github/actions/get-release-type
        with:
          TAG: ${{ steps.create_variables.outputs.release_tag }}

  extended_integration_tests:
    name: extended_integration_tests
    runs-on: daq
    timeout-minutes: 90
    needs: make_variables
    outputs:
      integtest_log_dir: ${{ steps.integtest_logs.outputs.integtest_log_dir }}
      logs_exist: ${{ steps.integtests.outputs.logs_exist }}
    env:
      DBT_AREA_ROOT: ${{ needs.make_variables.outputs.tag }}
      RELEASE_TAG: ${{ needs.make_variables.outputs.tag }}
      DAQ_RELEASE_PATH: ${{ needs.make_variables.outputs.daq_release_path }}
    defaults:
      run:
        shell: bash

    steps:
    - name: checkout daq-release
      uses: actions/checkout@v6
      with:
        path: ${{ needs.make_variables.outputs.daq_release_path }}

    - name: Create build area
      env:
        DBT_ARGS: ${{ needs.make_variables.outputs.dbt_args }}
        COREDAQ_MANIFEST: ${{ needs.make_variables.outputs.coredaq_manifest }}
        FDDAQ_MANIFEST: ${{ needs.make_variables.outputs.fddaq_manifest }}
      run: |
        source /cvmfs/dunedaq.opensciencegrid.org/setup_dunedaq.sh
        setup_dbt latest_v5

        dbt-create $DBT_ARGS "$RELEASE_TAG" "$DBT_AREA_ROOT"

        cd $DBT_AREA_ROOT
        source env.sh
        cd ../$DAQ_RELEASE_PATH/scripts
        ./checkout-daq-package.py -i ../$COREDAQ_MANIFEST -a -o ${DBT_AREA_ROOT}/sourcecode
        ./checkout-daq-package.py -i ../$FDDAQ_MANIFEST -a -o ${DBT_AREA_ROOT}/sourcecode
        #./checkout-daq-package.py -p dfmodules -i ../$COREDAQ_MANIFEST -o ${DBT_AREA_ROOT}/sourcecode
        #./checkout-daq-package.py -p trigger -i ../$COREDAQ_MANIFEST -o ${DBT_AREA_ROOT}/sourcecode
        echo "DBT_AREA_ROOT=$DBT_AREA_ROOT" >> "$GITHUB_ENV"

    - name: Run integration tests
      id: integtests
      run: |
        cd $DBT_AREA_ROOT
        # daqsystemtest and listrev tests are already run as part of the nightly integration tests
        rm -rf sourcecode/daqsystemtest
        rm -rf sourcecode/listrev
        source env.sh
        dbt-workarea-env
        dbt-build --integtest | tee integtest_full_output.log

    - name: Check and set integration test log directory
      if: always()
      id: integtest_logs
      run: |
        # Log directory is the last non-empty line of output
        logs_exist="false"
        integtest_log_dir=$(readlink -f $DBT_AREA_ROOT/log/integtest_tests_* | tail -n 1)

        echo "integtest_log_dir: $integtest_log_dir"
        echo "integtest_log_dir=${integtest_log_dir}" >> "$GITHUB_OUTPUT"

        if [[ ! -d $integtest_log_dir ]]; then
          echo "ERROR: No integtest log directory found under $DBT_AREA_ROOT/log."
          exit 2
        fi
        if [[ -z $(ls -A $integtest_log_dir) ]]; then
          echo "ERROR: The log directory $integtest_log_dir is empty."
          exit 3
        fi

        logs_exist="true"
        echo "logs_exist=${logs_exist}"
        echo "logs_exist=${logs_exist}" >> "$GITHUB_OUTPUT"
    - name: Upload integtest logs
      uses: actions/upload-artifact@v7
      with:
        name: extended_integtest_logs
        path: ${{ steps.integtest_logs.outputs.integtest_log_dir }}
        if-no-files-found: error
    - name: Store pytest logs
      env:
        PERSISTENT_LOG_DIR: ${{ needs.make_variables.outputs.persistent_log_dir }}
      id: move_logs
      run: |
        mkdir -p "$PERSISTENT_LOG_DIR"

        max_kb=10000000
        total_log_dir_size=0

        mapfile -t recent_pytest_dirs < <(find /tmp/pytest-of-dunedaq/ -mindepth 1 -maxdepth 1 -mmin -120 -type d)
        echo "Traversing pytest directories less than 2 hours old: ${recent_pytest_dirs[@]}"
        for dir in "${recent_pytest_dirs[@]}"; do
          if [[ ! -d "$dir" ]]; then
            echo "$dir is not a directory. Continuing..."
            continue
          fi
          if [[ "$(basename $dir)" == "pytest-current" ]]; then
            echo "Skipping pytest-current..."
            continue
          fi
          dir_size_kb=$(du -sk $dir | awk '{print $1}')
          echo "Size of $dir: $(du -sh $dir | awk '{print $1}')"

          total_log_dir_size=$(( total_log_dir_size + dir_size_kb))
          if (( total_log_dir_size > max_kb )); then
            echo "ERROR: $dir of size $dir_size_kb would make $PERSISTENT_LOG_DIR exceed $max_kb. Exiting..." >&2
            exit 2
          fi

          rsync -a --no-links --prune-empty-dirs \
            --chmod=D755,F644 \
            "$dir"/ "$PERSISTENT_LOG_DIR/$(basename "$dir")"/
        done
    - name: Upload logs as artifact
      if: success() || failure()
      uses: actions/upload-artifact@v7
      with:
        name: pytest-logs-extended-${{ needs.make_variables.outputs.timestamp }}
        path: ${{ needs.make_variables.outputs.persistent_log_dir  }}
    - name: Clean up files from daq.fnal.gov
      if: always()
      env:
        RELEASE_TAG: ${{ needs.make_variables.outputs.tag }}
        INTEGTEST_XML_PATH: ${{ needs.make_variables.outputs.integtest_output_path }}
      run: |
        rm -rf ${{ needs.make_variables.outputs.integtest_output_path }} || true

        if [[ -d "$INTEGTEST_XML_PATH" ]]; then
          echo "Removing $INTEGTEST_XML_PATH"
          rm -rf $INTEGTEST_XML_PATH
        fi

        if [[ -d "$DAQ_RELEASE_PATH" ]]; then
          echo "Removing $DAQ_RELEASE_PATH"
          rm -rf $DAQ_RELEASE_PATH
        fi

        if [[ -d "$RELEASE_TAG" ]]; then
          echo "Removing $RELEASE_TAG"
          rm -rf $RELEASE_TAG
        fi
    - name: Delete old log directories
      if: always()
      run: |
        old_dirs=$(find /home/nfs/dunedaq/github-actions -mindepth 1 -maxdepth 1 -type d -mtime +7)
        if [[ -n "$old_dirs" ]]; then
          echo "Removing the following directories that are more than 7 days old: $old_dirs"
          rm -rf $old_dirs
        fi
    - name: Clean up stale gunicorn processes
      if: always()
      run: |
        /home/nfs/dunedaq/kill_stale_gunicorn_processes.sh

  parse_and_upload_results:
    runs-on: ubuntu-latest
    needs: [make_variables, extended_integration_tests]
    if: ${{ needs.extended_integration_tests.result == 'success' }}
    steps:
    - uses: actions/checkout@v6
    - uses: actions/download-artifact@v8
      with:
        name: extended_integtest_logs
        path: extended_integtest_logs
    - name: Generate summary tables
      continue-on-error: true
      run: |
        python scripts/github-ci/integtest_xml_parser.py --input-directory extended_integtest_logs/
        cat pytest_summary_table.md >> $GITHUB_STEP_SUMMARY
    - name: Upload markdown summary as artifact
      uses: actions/upload-artifact@v7
      with:
        name: nightly_extended_integtest_summary
        path: pytest_summary_table.md
    - name: Upload json summary as artifact
      uses: actions/upload-artifact@v7
      with:
        if-no-files-found: error
        name: nightly_extended_integtest_json
        path: pytest_summary.json

  send_slack_message:
    if: (always()) && ((github.event_name != 'workflow_dispatch') || (github.event_name == 'workflow_dispatch' && github.event.inputs.send-slack-message == 'yes'))
    needs: [make_variables, extended_integration_tests, parse_and_upload_results]
    uses: ./.github/workflows/slack-notification.yml
    with:
      release_tag: ${{ needs.make_variables.outputs.tag }}
      integtest_log_dir: ${{ needs.make_variables.outputs.persistent_log_dir }}
      artifact_name: nightly_extended_integtest_json
    secrets:
      slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}


