name: hello-podman
on: 
  push:
    branches:
      - 'amogan/podman_workflow'


jobs:
  build_alma9:
    name: Build alma9 slim externals with Buildah
    runs-on: daq
    permissions:
      packages: write
      contents: read
    env:
        IMAGE_NAME: alma9-slim-externals:v2.1
        USERNAME: dune-daq
        REGISTRY: ghcr.io
    steps:
      - name: Print disk space
        run: |
            df -h
      - name: Print podman debug
        run: podman info --debug
      - name: Print Docker env
        run: env | grep DOCKER
      - name: Podman Login
        uses: redhat-actions/podman-login@v1
        with:
          registry: ${{ env.REGISTRY }}
          #username: ${{ github.actor }}
          username: ${{ env.USERNAME }}
          password: ${{ secrets.GITHUB_TOKEN }}
          auth_file_path: '$HOME/.docker/config.json'

      - name: Build Image
        uses: redhat-actions/buildah-build@v2
        with:
          base-image: ${{ env.REGISTRY }}/${{ env.USERNAME }}/${{ env.IMAGE_NAME }}
          image: my-new-image
          tags: v0.1

