name: Integration test workflow

permissions:
  contents: read

on:
  schedule:
    - cron: "0 5 * * *"

  workflow_dispatch:
    inputs:
      send-slack-message:
        description: 'whether to send a message to #daq-release-notifications on completion'
        default: 'no'
      release-tag:
        description: >-
          Release to test, e.g., NFD_DEV_YYMMDD_A9, fddaq-vX.Y.Z-a9, etc.
          Default: last_fddaq (latest nightly)
        required: false
        default: 'last_fddaq'

jobs:
  make_variables:
    name: create nightly tag, timestamp, etc.
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.create_variables.outputs.release_tag }}
      timestamp: ${{ steps.create_variables.outputs.timestamp }}
      persistent_log_dir: ${{ steps.create_variables.outputs.persistent_log_dir }}
      integtest_output_path: ${{ steps.create_variables.outputs.integtest_output_path }}
      dbt_args: ${{ steps.release_type.outputs.dbt_args }}
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v6
      - id: create_variables
        run: |
          tag="${{ inputs.release-tag }}"
          release_tag="${tag:-last_fddaq}"
          if [[ "$release_tag" == "last_fddaq" ]]; then
            release_tag="NFD_DEV_$(date +%y%m%d)_A9"
          fi
          timestamp=$(date +"%Y-%m-%d-%H%M%Z")
          persistent_log_dir=/home/nfs/dunedaq/github-actions/pytest-logs-${timestamp}
          integtest_output_path=/home/nfs/dunedaq/actions-runner/_work/daq-release/daq-release/integration_tests_${release_tag}

          echo "release_tag=${release_tag}"  >>  "$GITHUB_OUTPUT"
          echo "timestamp=${timestamp}" >> "$GITHUB_OUTPUT"
          echo "persistent_log_dir=${persistent_log_dir}" >> "$GITHUB_OUTPUT"
          echo "integtest_output_path=${integtest_output_path}" >> "$GITHUB_OUTPUT"
          cat "$GITHUB_OUTPUT"
      - name: Get release type
        id: release_type
        uses: ./.github/actions/get-release-type
        with:
          TAG: ${{ steps.create_variables.outputs.release_tag }}

  integration_tests:
    name: integration_tests
    runs-on: daq
    timeout-minutes: 30
    needs: make_variables
    strategy:
        fail-fast: false
        matrix:

            test_name: [
                        "listrev_test",
                        "3ru_1df_multirun_test",
                        "3ru_3df_multirun_test",
                        "disabled_tpg_test",
                        "example_system_test",
                        "fake_data_producer_test",
                        "long_window_readout_test",
                        "minimal_system_quick_test",
                        "readout_type_scan_test",
                        "small_footprint_quick_test",
                        "tpreplay_test",
                        "tpstream_writing_test"
                       ]
    defaults:
      run:
        shell: bash

    steps:
    - name: setup release and run tests
      env:
        RELEASE_TAG: ${{needs.make_variables.outputs.tag}}
        DBT_ARGS: ${{ needs.make_variables.outputs.dbt_args }}
        INTEGTEST_OUTPUT_PATH: ${{needs.make_variables.outputs.integtest_output_path}}
      id: setup_and_run_test
      run: |
        mkdir -p $INTEGTEST_OUTPUT_PATH
        cd $INTEGTEST_OUTPUT_PATH
        echo "Am in $(pwd)"
        echo "INTEGTEST_OUTPUT_PATH: $INTEGTEST_OUTPUT_PATH"
        source /cvmfs/dunedaq.opensciencegrid.org/setup_dunedaq.sh
        setup_dbt latest_v5
        
        dbt-setup-release $DBT_ARGS $RELEASE_TAG

        TEST_PATH=""
        TEST_SOURCE=""
        if [[ "${{ matrix.test_name }}" == "listrev_test" ]]; then
          TEST_PATH=$LISTREV_SHARE/integtest
          TEST_SOURCE=listrev
        else
          TEST_PATH=$DAQSYSTEMTEST_SHARE/integtest
          TEST_SOURCE=daqsystemtest
        fi

        pytest_retval=0
        pytest --tb=short --junit-xml=${TEST_SOURCE}_${{ matrix.test_name }}_results.xml \
                $TEST_PATH/${{ matrix.test_name }}.py || { pytest_retval=$?; true; }
        test $pytest_retval == 0 || false

    - name: Copy log to persistent area
      if: always()
      env:
        PERSISTENT_LOG_DIR: ${{needs.make_variables.outputs.persistent_log_dir}}
      run: |
        max_kb=10000000
        total_log_dir_size=0
        pytest_current_dir=/tmp/pytest-of-dunedaq/pytest-current/

        [[ -d "$pytest_current_dir" ]] || { echo "No pytest directory found for ${{ matrix.test_name }}"; exit 1; }
        dir_size_kb=$(du -sk $pytest_current_dir | awk '{print $1}')
        echo "Size of $pytest_current_dir: $(du -sh $pytest_current_dir | awk '{print $1}')"

        if (( dir_size_kb > max_kb )); then
          echo "ERROR: ${{ matrix.test_name }} log directory $pytest_current_dir of size $dir_size_kb would make $PERSISTENT_LOG_DIR exceed $max_kb. Exiting..." >&2
          exit 2
        fi

        mkdir -p $PERSISTENT_LOG_DIR/${{ matrix.test_name }}
        rsync -a --no-links --prune-empty-dirs \
          --chmod=D755,F644 \
          "$pytest_current_dir"/ "$PERSISTENT_LOG_DIR/${{ matrix.test_name }}"/

  store_and_upload_logs:
    runs-on: daq
    timeout-minutes: 5
    needs: [make_variables, integration_tests]
    if: always()
    steps:
    - name: Upload pytest logs
      uses: actions/upload-artifact@v7
      with:
        name: pytest-logs-${{ needs.make_variables.outputs.timestamp }}
        path: ${{ needs.make_variables.outputs.persistent_log_dir }}
        if-no-files-found: error
    - name: Upload junit xml files
      uses: actions/upload-artifact@v7
      with:
        name: junit-xml
        path: ${{ needs.make_variables.outputs.integtest_output_path }}
        if-no-files-found: error
    - name: Cleanup files
      run: |
        rm -rf ${{ needs.make_variables.outputs.integtest_output_path }}
    - name: Delete old log directories
      run: |
        old_dirs=$(find /home/nfs/dunedaq/github-actions -mindepth 1 -maxdepth 1 -type d -mtime +7)
        echo "Removing the following directories that are more than 7 days old: $old_dirs"
        rm -rf $old_dirs
    # Integration tests can sometimes collide with stale processes, leading to timeout
    - name: Kill stale gunicorn processes
      run: |
        /home/nfs/dunedaq/kill_stale_gunicorn_processes.sh

  parse_and_upload_results:
    runs-on: ubuntu-latest
    needs: [make_variables, store_and_upload_logs]
    if: always() && needs.store_and_upload_logs.result == 'success'
    steps:
    - name: Checkout daq-release
      uses: actions/checkout@v6
    - name: Download pytest logs
      uses: actions/download-artifact@v8
    - name: Generate summary tables
      run: |
        cd scripts/github-ci/
        python integtest_xml_parser.py \
               --input-directory ${{ github.workspace }}/junit-xml
        cat pytest_summary_table.md >> $GITHUB_STEP_SUMMARY
    - name: Upload markdown summary as artifact
      uses: actions/upload-artifact@v7
      with:
        if-no-files-found: error
        name: nightly_integtest_summary
        path: scripts/github-ci/pytest_summary_table.md
    - name: Upload json summary as artifact
      uses: actions/upload-artifact@v7
      with:
        if-no-files-found: error
        name: nightly_integtest_json
        path: scripts/github-ci/pytest_summary.json

  send_slack_message:
    if: (always()) && ((github.event_name != 'workflow_dispatch') || (github.event_name == 'workflow_dispatch' && github.event.inputs.send-slack-message == 'yes'))
    needs: [make_variables, parse_and_upload_results]
    uses: ./.github/workflows/slack-notification.yml
    with:
      release_tag: ${{ needs.make_variables.outputs.tag }}
      integtest_log_dir: ${{ needs.make_variables.outputs.persistent_log_dir }}
      artifact_name: nightly_integtest_json
    secrets: 
      slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}


