name: Nightly workflow

on:
  #push:
    #branches: [ develop ]
  schedule:
    - cron: "0 5 * * *"

  workflow_dispatch:
    inputs:
      name:
        description: 'Manual start the CI workflow'
        default: 'Yes'
        required: true

jobs:
  bulid_the_develop_release:
    name: ${{ matrix.os_name }}_build_dev_release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - image: "dunedaq/sl7-minimal:dev-ext"
            os_name: "c7"
          - image: "dunedaq/c8-minimal:dev-ext"
            os_name: "c8"
    container:
      image: ${{ matrix.image }}
    env:
      DBT_AREA_FILE: "dbt-settings"
    defaults:
      run:
        shell: bash

    steps:
    - name: Start the CI
      run: echo "Start the CI anyway ${{ github.event.inputs.name }}"

    - name: Checkout daq-release
      uses: actions/checkout@v2
      with:
        repository: DUNE-DAQ/daq-release
        path: daq-release
        
    - name: setup dev area and checkout code
      run: |
          source /cvmfs/dunedaq.opensciencegrid.org/setup_dunedaq.sh
          setup_dbt latest
          dbt-create.sh -r $GITHUB_WORKSPACE/daq-release/configs dunedaq-develop dev-${{ matrix.os_name }}
          cd dev-${{ matrix.os_name }}
          cp $GITHUB_WORKSPACE/daq-release/configs/dunedaq-develop/release_manifest.sh .
          $GITHUB_WORKSPACE/daq-release/scripts/checkout-package.sh -f ./release_manifest.sh -a -o sourcecode
    
    - name: setup build env and build the dev release
      run: |
          cd $GITHUB_WORKSPACE/dev-${{ matrix.os_name }}
          source dbt-env.sh
          dbt-workarea-env -s externals || true
          dbt-build.py

    - name: create release directory
      run: |
          [[ ${{ matrix.os_name }} == "c8" ]] && nightly_tag="${nightly_tag}-${{ matrix.os_name }}"
          nightly_workdir="$GITHUB_WORKSPACE/nightly-${{ matrix.os_name }}"
          mkdir -p ${nightly_workdir}/${nightly_tag}
          
          cd $GITHUB_WORKSPACE/dev-${{ matrix.os_name }}
          source dbt-env.sh
          dbt-workarea-env -s externals || true

          $GITHUB_WORKSPACE/daq-release/scripts/create-ups-products-area.sh -t ${nightly_workdir}/${nightly_tag}/packages
          cp $GITHUB_WORKSPACE/daq-release/configs/dunedaq-develop/dbt-build-order.cmake ${nightly_workdir}/${nightly_tag}
          cp $GITHUB_WORKSPACE/daq-release/configs/dunedaq-develop/pyvenv_requirements.txt ${nightly_workdir}/${nightly_tag}
          clonevirtualenv.py $GITHUB_WORKSPACE/dev-${{ matrix.os_name }}/dbt-pyvenv ${nightly_workdir}/${nightly_tag}/dbt-pyvenv
          $GITHUB_WORKSPACE/daq-release/scripts/upsify-daq-pkgs.py -w $GITHUB_WORKSPACE/dev-${{ matrix.os_name }} -c ${{ matrix.os_name }} -i -o ${nightly_workdir}/${nightly_tag}/packages
          echo "PROGRESS: created ups products for DAQ packages."
          echo " dune_daqpackages=(" >> ${DBT_AREA_ROOT}/${DBT_AREA_FILE}
          echo "PROGRESS: updating dbt-settings.sh"
          cp $GITHUB_WORKSPACE/daq-release/configs/dunedaq-develop/dbt-settings.sh ${DBT_AREA_ROOT}/${DBT_AREA_FILE}
          cd ${nightly_workdir}/${nightly_tag}/packages
          find . -type d -name "*.version"|grep -v ups|sed 's/\.\//"/g'|sed 's/\.version/ e19:prof\"/g'|tr '/' ' '>> ${DBT_AREA_ROOT}/${DBT_AREA_FILE}
          echo ")">> ${DBT_AREA_ROOT}/${DBT_AREA_FILE}
          
          sed -i 's,dunedaq-develop,'"$nightly_tag"',' ${DBT_AREA_ROOT}/${DBT_AREA_FILE}
          sed -i 's,.*externals.*,"    /cvmfs/dunedaq-development.opensciencegrid.org/nightly/'"$nightly_tag"'/externals,' ${DBT_AREA_ROOT}/${DBT_AREA_FILE}
          sed -i 's,.*packages.*,"    /cvmfs/dunedaq-development.opensciencegrid.org/nightly/'"$nightly_tag"'/packages,' ${DBT_AREA_ROOT}/${DBT_AREA_FILE}

          # prepare external dir 
          $GITHUB_WORKSPACE/daq-release/scripts/create-ups-links.sh ${nightly_workdir}/${nightly_tag}/externals
          
          mv ${DBT_AREA_ROOT}/${DBT_AREA_FILE} ${nightly_workdir}/${nightly_tag}/dbt-settings.sh
          cd ${nightly_workdir}
          #[[ ${{ matrix.os_name }} == "c7" ]] && ln -s ${nightly_tag} last_successfull || ln -s ${nightly_tag} last_successfull_cs8
          tar zcvf dunedaq-${nightly_tag}.tar.gz ${nightly_tag}
          rm -rf ${nightly_tag}

    - name: upload nightly tarball
      uses: actions/upload-artifact@v2
      with:
        name: nightly_release_${{ matrix.os_name }}
        path: ${{ github.workspace }}/nightly-${{ matrix.os_name }}

    - name: upload build log file
      uses: actions/upload-artifact@v2
      with:
        name: build_log_${{ matrix.os_name }}
        path: ${{ github.workspace }}/dev-${{ matrix.os_name }}/log
