name: Nightly dbt regression tests

permissions:
  contents: read

on:
  workflow_dispatch:
    inputs:
      send-slack-message:
        description: 'whether to send a message to #daq-release-notifications on completion'
        default: 'no'
  schedule:
    - cron: "0 8 * * *"

jobs:
  run_dbt_commands:
    name: Run dbt test script
    runs-on: ubuntu-latest
    container:
      image: almalinux:9
    timeout-minutes: 20
    defaults:
      run:
        shell: bash
    steps:
    - uses: cvmfs-contrib/github-action-cvmfs@d93d881391926e8146776c13345c3e23d6393acd
      with:
        cvmfs_repositories: 'dunedaq-development.opensciencegrid.org'
    - uses: actions/checkout@v6
    - name: Run dbt test script
      run: | 
        ./scripts/test_daq-buildtools.sh

  send_slack_message:
    if: (github.event_name != 'workflow_dispatch' && failure()) || (github.event_name == 'workflow_dispatch' && github.event.inputs.send-slack-message == 'yes')
    needs: run_dbt_commands
    uses: ./.github/workflows/slack-notification.yml
    secrets: 
      slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
