name: Nightly code check workflow

on:
  workflow_dispatch:
    inputs:
      send-slack-message:
        description: 'whether to send a message to #daq-release-notifications on completion'
        default: 'no'
  schedule:
    - cron: "30 10 * * *"

jobs:
  make_variables:
    name: create nightly tag
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.create_nightly_tag.outputs.nightly_tag }} 
    defaults:
      run:
        shell: bash
    steps:
      - id: create_nightly_tag
        run: |
          date_tag=$(date +%y%m%d)
          echo "nightly_tag=NFD_DEV_${date_tag}_A9"  >>  "$GITHUB_OUTPUT"
  
  run_unittests:
    needs: make_variables
    uses: ./.github/workflows/unit-tests.yml
    with:
      release_tag: ${{ needs.make_variables.outputs.tag }}

  run_checks:
    name: Run linting and integration tests
    runs-on: daq
    needs: [make_variables, run_unittests]
    timeout-minutes: 30
    outputs:
      integtest_log_dir: ${{ steps.integtests.outputs.integtest_log_dir }}
    defaults:
      run:
        shell: bash
    steps:
    - name: Checkout daq-release
      uses: actions/checkout@v4
      with:
        path: daq-release-code-checks
    - name: Create build area
      run: |
        source /cvmfs/dunedaq.opensciencegrid.org/setup_dunedaq.sh
        setup_dbt latest_v5
        dbt-create -n ${{ needs.make_variables.outputs.tag }}
        cd ${{ needs.make_variables.outputs.tag }}
        source env.sh
        cd ../daq-release-code-checks/scripts
        #cd ${{ github.workspace }}/daq-release-code-checks/scripts
        ./checkout-daq-package.py -i ../configs/coredaq/coredaq-develop/release.yaml -a -o ${DBT_AREA_ROOT}/sourcecode
        ./checkout-daq-package.py -i ../configs/fddaq/fddaq-develop/release.yaml -a -o ${DBT_AREA_ROOT}/sourcecode
        #./checkout-daq-package.py -p hdf5libs -b develop -i ../configs/coredaq/coredaq-develop/release.yaml -o ${DBT_AREA_ROOT}/sourcecode
        #./checkout-daq-package.py -p flxlibs -b develop -i ../configs/fddaq/fddaq-develop/release.yaml -o ${DBT_AREA_ROOT}/sourcecode
        echo "DBT_AREA_ROOT=$DBT_AREA_ROOT" >> "$GITHUB_ENV"
    - name: Run clang formatting
      run: |
        cd $DBT_AREA_ROOT
        source env.sh
        cd sourcecode
        dbt-clang-format.sh . --view-differences-only --markdown-summary
        cat clang_format_summary_table.md >> $GITHUB_STEP_SUMMARY

    - name: Run integration tests
      id: integtests
      run: |
        cd $DBT_AREA_ROOT
        # daqsystemtest and listrev tests are already run as part of the nightly integration tests
        rm -rf sourcecode/daqsystemtest
        rm -rf sourcecode/listrev
        source env.sh
        dbt-workarea-env
        dbt-build --integtest | tee integtest_full_output.log
        # Log directory is the last non-empty line of output
        integtest_log_dir=$(readlink -f $DBT_AREA_ROOT/log/integtest_tests_* | tail -n 1)
        echo "integtest_log_dir=${integtest_log_dir}" >> "$GITHUB_OUTPUT"
        echo "integtest_log_dir: $integtest_log_dir"

  parse_integtest_results:
    runs-on: daq
    needs: [make_variables, run_unittests, run_checks]
    steps:
    - name: Generate summary tables
      run: |
        cd daq-release-code-checks/scripts/github-ci/
        python integtest_xml_parser.py --input-directory ${{ needs.run_checks.outputs.integtest_log_dir }}
        cat pytest_summary_table.md >> $GITHUB_STEP_SUMMARY

  send_slack_message:
    if: (github.event_name != 'workflow_dispatch' && failure()) || (github.event_name == 'workflow_dispatch' && github.event.inputs.send-slack-message == 'yes')
    needs: parse_integtest_results
    uses: ./.github/workflows/slack-notification.yml
    secrets: 
      slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}

  cleanup_test_area:
    runs-on: daq
    if: always()
    needs: [make_variables, parse_integtest_results]
    steps:
      - name: Remove test directory and daq-release
        run: |
          rm -rf daq-release-code-checks
          rm -rf ${{ needs.make_variables.outputs.tag }}