name: Update pypi-repo

on:
  schedule:
    - cron: "0 1 * * *"
    # update pypi-repo "0 1 * * *"
    # publish pypi-repo to cvmfs "30 21 * * *(CST/CDT)" 30 1/2 * * *
    # c8-cvmfs docker build on "0 3 * * *"
    # sl7-cvmfs docker build on "0 4 * * *"
    # nighlty release build on "0 5 * * *"
    # publish to cvmfs on "0 1 * * *(CST/CDT)" 0 6/7 * * *
    # package CI build on "0 7 * * *"

  workflow_dispatch:

jobs:
  update_pypi_repo:
    name: update_pypi_repo
    runs-on: ubuntu-latest
    container:
      image: dunedaq/c8-minimal:spack-externals
    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout daq-release
      uses: actions/checkout@v3
      with:
        repository: DUNE-DAQ/daq-release
        path: daq-release

    - name: install pip2pi
      run: |
          mkdir -p $GITHUB_WORKSPACE/workdir
          cd $GITHUB_WORKSPACE/workdir
          source `realpath /cvmfs/dunedaq.opensciencegrid.org/spack-externals/spack-installation/share/spack/setup-env.sh`
          spack load py-pyyaml@5.3.1
          python -m venv pypi-repo-venv
          source pypi-repo-venv/bin/activate
          echo "activated pyvenv"
          pip install --upgrade pip
          pip install https://github.com/dingp/pip2pi/archive/1.1.2.tar.gz
        
    - name: parse release_manifest and install all pkgs
      run: |
          cd $GITHUB_WORKSPACE/workdir
          source `realpath /cvmfs/dunedaq.opensciencegrid.org/spack-externals/spack-installation/share/spack/setup-env.sh`
          spack load py-pyyaml@5.3.1
          source pypi-repo-venv/bin/activate
          manifest_file="$GITHUB_WORKSPACE/daq-release/configs/dunedaq-develop/dunedaq-develop.yaml"
          repo_path="/cvmfs/dunedaq.opensciencegrid.org/pypi-repo"
          $GITHUB_WORKSPACE/daq-release/scripts/create-pypi-repo.sh $manifest_file $repo_path
          du -sh $repo_path
          rsync -rvplt $repo_path $GITHUB_WORKSPACE
          cd $GITHUB_WORKSPACE
          tar zcvf pypi-repo.tar.gz pypi-repo
          du -sh pypi-repo.tar.gz

    - name: generaete pyvenv_requirements.txt and test installing dbt-pyvenv
      run: |
          cd $GITHUB_WORKSPACE/workdir
          source `realpath /cvmfs/dunedaq.opensciencegrid.org/spack-externals/spack-installation/share/spack/setup-env.sh`
          spack load py-pyyaml@5.3.1
          $GITHUB_WORKSPACE/daq-release/scripts/spack/make-release-repo.py -o  $GITHUB_WORKSPACE --pyvenv-requirements -i $GITHUB_WORKSPACE/daq-release/configs/dunedaq-develop/dunedaq-develop.yaml
          python -m venv dbt-pyvenv
          source dbt-pyvenv/bin/activate
          python -m pip install -r $GITHUB_WORKSPACE/pyvenv_requirements.txt

    
    - name: upload pypi-repo
      uses: actions/upload-artifact@v3
      with:
        name: pypi-repo
        path: ${{ github.workspace }}/pypi-repo.tar.gz

    - name: upload pyvenv_requirements.txt
      uses: actions/upload-artifact@v3
      with:
        name: pyvenv_requirements
        path: ${{ github.workspace }}/pyvenv_requirements.txt
