name: Alma9 Spack Nightly Workflow

on:
  schedule:
    - cron: "0 3 * * *"

  workflow_dispatch:
    inputs:
      tag-prefix:
        description: 'nightly tag prefix'
        default: ''
      feature-branch:
        description: 'feature branch to be used across all DAQ repos wherever possible.'
        default: develop
      cvmfs-deployment:
        description: 'whether to deploy the release to cvmfs'
        default: 'no'

jobs:
  make_nightly_tag:
    name: create nightly tag
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.create_nightly_tag.outputs.nightly_tag }} 
    defaults:
      run:
        shell: bash
    steps:
      - id: create_nightly_tag
        run: |
          date_tag=$(date +%y-%m-%d)
          echo "nightly_tag=${{ github.event.inputs.tag-prefix }}${date_tag}"  >>  "$GITHUB_OUTPUT"
          cat "$GITHUB_OUTPUT"

  build_the_develop_release_spack:
    name: build_dev_release_spack
    runs-on: isc01
    needs: make_nightly_tag
    container:
      image: ghcr.io/dune-daq/alma9-slim-externals:v2.0
    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout daq-release
      uses: actions/checkout@v4
      with:
        path: daq-release

    - name: setup directories and install spack for the dunedaq release
      env:
        NIGHTLY_TAG: ${{needs.make_nightly_tag.outputs.tag}}
      run: |
          export BASE_RELEASE_DIR=/cvmfs/dunedaq-development.opensciencegrid.org/nightly/NAB${NIGHTLY_TAG}
          export DET_RELEASE_DIR=/cvmfs/dunedaq-development.opensciencegrid.org/nightly/NAFD${NIGHTLY_TAG}
          export OS=almalinux9
          source daq-release/.github/workflows/wf-setup-tools.sh

          daq-release/scripts/spack/build-release.sh $BASE_RELEASE_DIR $DET_RELEASE_DIR dune $OS

          cd $BASE_RELEASE_DIR/../
          tar_and_stage_release ${BASE_RELEASE_TAG}

    - name: upload spack nightly tarball for dunedaq
      uses: actions/upload-artifact@v3
      with:
        name: nightly_dunedaq
        path: ${{ github.workspace }}/tarballs_for_upload/NAB${{needs.make_nightly_tag.outputs.tag}}.tar.gz

    - name: setup directories and install spack for the fddaq release
      env:
        NIGHTLY_TAG: ${{needs.make_nightly_tag.outputs.tag}}
      run: |
          export BASE_RELEASE_DIR=/cvmfs/dunedaq-development.opensciencegrid.org/nightly/NAB${NIGHTLY_TAG}
          export DET_RELEASE_DIR=/cvmfs/dunedaq-development.opensciencegrid.org/nightly/NAFD${NIGHTLY_TAG}
          export OS=almalinux9
          source daq-release/.github/workflows/wf-setup-tools.sh

          daq-release/scripts/spack/build-release.sh $BASE_RELEASE_DIR $DET_RELEASE_DIR fd $OS

          cd $DET_RELEASE_DIR/../
          tar_and_stage_release ${DET_RELEASE_TAG}

    - name: upload spack nightly tarball for fddaq
      uses: actions/upload-artifact@v3
      with:
        name: nightly_fddaq
        path: ${{ github.workspace }}/tarballs_for_upload/NAFD${{needs.make_nightly_tag.outputs.tag}}.tar.gz

    - name: setup directories and install spack for the nddaq release
      env:
        NIGHTLY_TAG: ${{needs.make_nightly_tag.outputs.tag}}
      run: |
          export BASE_RELEASE_DIR=/cvmfs/dunedaq-development.opensciencegrid.org/nightly/NAB${NIGHTLY_TAG}
          export DET_RELEASE_DIR=/cvmfs/dunedaq-development.opensciencegrid.org/nightly/NAND${NIGHTLY_TAG}
          export OS=almalinux9
          source daq-release/.github/workflows/wf-setup-tools.sh

          daq-release/scripts/spack/build-release.sh $BASE_RELEASE_DIR $DET_RELEASE_DIR nd $OS

          cd $DET_RELEASE_DIR/../
          tar_and_stage_release ${DET_RELEASE_TAG}

    - name: upload spack nightly tarball for nddaq
      uses: actions/upload-artifact@v3
      with:
        name: nightly_nddaq
        path: ${{ github.workspace }}/tarballs_for_upload/NAND${{needs.make_nightly_tag.outputs.tag}}.tar.gz


  update_image:
    name: update_spack_image_nightly
    runs-on: isc01
    strategy:
      matrix:
        include:
          - image: "ghcr.io/dune-daq/alma9-slim-externals"
            os_name: "al9"
    needs: [build_the_develop_release_spack, make_nightly_tag] 
    environment: dockerhub
    permissions:
      packages: write
      contents: read

    steps:
      - name: clean docker-build
        run: |
            mkdir -p ${GITHUB_WORKSPACE}/docker-build 
            rm -rf ${GITHUB_WORKSPACE}/docker-build/*

      - name: Download spack nightly release tarball artifact for dunedaq
        uses: actions/download-artifact@v3
        with:
          name: nightly_dunedaq
          path: ${{ github.workspace }}/docker-build

      - name: Download spack nightly release tarball artifact for fddaq
        uses: actions/download-artifact@v3
        with:
          name: nightly_fddaq
          path: ${{ github.workspace }}/docker-build

      - name: Download spack nightly release tarball artifact for nddaq
        uses: actions/download-artifact@v3
        with:
          name: nightly_nddaq
          path: ${{ github.workspace }}/docker-build

      - name: prepare cvmfs mirror spack-nightly
        env:
          NIGHTLY_TAG: ${{needs.make_nightly_tag.outputs.tag}}
        run: |
            cd ${{ github.workspace }}/docker-build
            mkdir -p nightly
            export EXT_VERSION=v2.0
            image_name="${{ matrix.image }}:${EXT_VERSION}"

            cd nightly
            dunedaq_tag="NAB${NIGHTLY_TAG}"
            tar xvf ../${dunedaq_tag}.tar.gz
            rm -rf ../${dunedaq_tag}.tar.gz

            fddaq_tag="NAFD${NIGHTLY_TAG}"
            tar xvf ../${fddaq_tag}.tar.gz
            rm -rf ../${fddaq_tag}.tar.gz
            ln -s ${fddaq_tag} last_fddaq
            cd last_fddaq; ln -s spack-*-gcc-* default; cd ..

            nddaq_tag="NAND${NIGHTLY_TAG}"
            tar xvf ../${nddaq_tag}.tar.gz
            rm -rf ../${nddaq_tag}.tar.gz
            ln -s ${nddaq_tag} last_nddaq
            cd last_nddaq; ln -s spack-*-gcc-* default; cd ..

            cd ..
            echo "FROM ${image_name}"> Dockerfile
            echo 'MAINTAINER John Freeman "jcfree@fnal.gov"' >> Dockerfile
            echo "ENV REFRESHED_AT ${NIGHTLY_TAG}" >> Dockerfile
            echo "COPY --from=ghcr.io/dune-daq/pypi-repo:latest /cvmfs/dunedaq.opensciencegrid.org/pypi-repo /cvmfs/dunedaq.opensciencegrid.org/pypi-repo" >> Dockerfile
            echo "ADD nightly /cvmfs/dunedaq-development.opensciencegrid.org/nightly" >> Dockerfile
            echo 'ENTRYPOINT ["/bin/bash"]' >> Dockerfile

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ matrix.image }}
          tags: |
            type=raw,value=spack-dev-v2.0

      - name: Build and push Docker images
        uses: docker/build-push-action@v5
        with:
          context: ${{ github.workspace }}/docker-build
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}


  generate_dbt_setup_release_env:
    name: generate_dbt_setup_release_env_${{ matrix.os_name }}
    runs-on: ubuntu-latest
    needs: update_image
    container:
      image: "ghcr.io/dune-daq/alma9-slim-externals:spack-dev-v2.0"
    defaults:
      run:
        shell: bash

    steps:
    
    - name: create dbt-setup-release-env.sh and daq_app_rte.sh for fddaq
      run: |
          export DET=fd
          source /cvmfs/dunedaq.opensciencegrid.org/setup_dunedaq.sh
          setup_dbt latest|| true
          dbt-setup-release -n last_${DET}daq
          declare -x > ${GITHUB_WORKSPACE}/${DET}daq-dbt-setup-release-env.sh
          declare -f >> ${GITHUB_WORKSPACE}/${DET}daq-dbt-setup-release-env.sh
          egrep "declare -x (PATH|.*_SHARE|CET_PLUGIN_PATH|DUNEDAQ_SHARE_PATH|LD_LIBRARY_PATH|LIBRARY_PATH|PYTHONPATH)=" ${GITHUB_WORKSPACE}/${DET}daq-dbt-setup-release-env.sh > ${GITHUB_WORKSPACE}/${DET}daq_app_rte.sh

    - name: create dbt-setup-release-env.sh and daq_app_rte.sh for nddaq
      run: |
          export DET=nd
          source /cvmfs/dunedaq.opensciencegrid.org/setup_dunedaq.sh
          setup_dbt latest|| true
          dbt-setup-release -n last_${DET}daq
          declare -x > ${GITHUB_WORKSPACE}/${DET}daq-dbt-setup-release-env.sh
          declare -f >> ${GITHUB_WORKSPACE}/${DET}daq-dbt-setup-release-env.sh
          egrep "declare -x (PATH|.*_SHARE|CET_PLUGIN_PATH|DUNEDAQ_SHARE_PATH|LD_LIBRARY_PATH|LIBRARY_PATH|PYTHONPATH)=" ${GITHUB_WORKSPACE}/${DET}daq-dbt-setup-release-env.sh > ${GITHUB_WORKSPACE}/${DET}daq_app_rte.sh

    - name: upload fddaq-dbt-setup-release-env.sh
      uses: actions/upload-artifact@v3
      with:
        name: fddaq-dbt_setup_release_env
        path: ${{ github.workspace }}/fddaq-dbt-setup-release-env.sh

    - name: upload fddaq_app_rte.sh
      uses: actions/upload-artifact@v3
      with:
        name: fddaq_app_rte
        path: ${{ github.workspace }}/fddaq_app_rte.sh

    - name: upload nddaq-dbt-setup-release-env.sh
      uses: actions/upload-artifact@v3
      with:
        name: nddaq-dbt_setup_release_env
        path: ${{ github.workspace }}/nddaq-dbt-setup-release-env.sh

    - name: upload nddaq_app_rte.sh
      uses: actions/upload-artifact@v3
      with:
        name: nddaq_app_rte
        path: ${{ github.workspace }}/nddaq_app_rte.sh

  publish_to_cvmfs:
    name: publish to cvmfs
    needs: generate_dbt_setup_release_env
    runs-on: isc01

    steps:
    - name: check_cvmfs_deployment
      id: do_deployment
      run: |
        cvmfs_deployment_input=${{ github.event.inputs.cvmfs-deployment }}
        cvmfs_deployment_flag=${cvmfs_deployment_input:-"yes"}
        echo "Do cvmfs deployment: ${cvmfs_deployment_flag}"
        [[ ${cvmfs_deployment_flag} == 'yes' ]] && exit 0 || exit 1
      continue-on-error: true

    - name: download fddaq-dbt-setup-release-env.sh
      if: steps.do_deployment.outcome == 'success'
      uses: actions/download-artifact@v3
      with:
        name: fddaq-dbt_setup_release_env
        path: ${{ github.workspace }}/fddaq-release

    - name: download fddaq_app_rte.sh
      if: steps.do_deployment.outcome == 'success'
      uses: actions/download-artifact@v3
      with:
        name: fddaq_app_rte
        path: ${{ github.workspace }}/fddaq-rte

    - name: download nddaq-dbt-setup-release-env.sh
      if: steps.do_deployment.outcome == 'success'
      uses: actions/download-artifact@v3
      with:
        name: nddaq-dbt_setup_release_env
        path: ${{ github.workspace }}/nddaq-release

    - name: download nddaq_app_rte.sh
      if: steps.do_deployment.outcome == 'success'
      uses: actions/download-artifact@v3
      with:
        name: nddaq_app_rte
        path: ${{ github.workspace }}/nddaq-rte

    - name: start docker container, and then rsync... 
      if: steps.do_deployment.outcome == 'success'
      run: |
        [[ ${DO_DEPLOYMENT} == 'no' ]] && exit 0

        IMAGE="ghcr.io/dune-daq/alma9-slim-externals:spack-dev-v2.0"

        cd $GITHUB_WORKSPACE
        cat << EOT > publish.sh
        #!/bin/bash
        
        
        source /cvmfs/dunedaq.opensciencegrid.org/tools/dbt/latest/env.sh
        dbt-setup-release -n last_fddaq
        
        export KRB5CCNAME=$(mktemp)
        /scratch-home/get-ticket.sh

        klist -l
        
        fd_release_dir=/cvmfs/dunedaq-development.opensciencegrid.org/nightly/last_fddaq
        mv /scratch/fddaq-rte/fddaq_app_rte.sh \$fd_release_dir/daq_app_rte.sh
        mv /scratch/fddaq-release/fddaq-dbt-setup-release-env.sh \$fd_release_dir/dbt-setup-release-env.sh
        nd_release_dir=/cvmfs/dunedaq-development.opensciencegrid.org/nightly/last_nddaq
        mv /scratch/nddaq-rte/nddaq_app_rte.sh \$nd_release_dir/daq_app_rte.sh
        mv /scratch/nddaq-release/nddaq-dbt-setup-release-env.sh \$nd_release_dir/dbt-setup-release-env.sh
        
        export CVMFS_SERVER="oasiscfs01.fnal.gov"
        export CVMFS_USER="cvmfsdunedaqdev"
        export REPO=dunedaq-development.opensciencegrid.org
        export DEST=/cvmfs/\$REPO/nightly
        
        spack clean -a
        # Open transaction
        ssh -o StrictHostKeyChecking=no -l \${CVMFS_USER} \${CVMFS_SERVER} "cvmfs_server transaction \${REPO}"
        # rsync
        cd /cvmfs/\$REPO
        rsync -e "ssh -o StrictHostKeyChecking=no" -rlpt --stats nightly/last_fddaq \${CVMFS_USER}@\${CVMFS_SERVER}:\$DEST
        rsync -e "ssh -o StrictHostKeyChecking=no" -rlpt --stats nightly/last_nddaq \${CVMFS_USER}@\${CVMFS_SERVER}:\$DEST
        rsync -e "ssh -o StrictHostKeyChecking=no" -rlpt --stats --delete-after nightly/N*-??-?? \${CVMFS_USER}@\${CVMFS_SERVER}:\$DEST
        # publish
        ssh -o StrictHostKeyChecking=no -l \${CVMFS_USER} \${CVMFS_SERVER} "cvmfs_server publish \${REPO}"

        rm -rf /scratch/*daq-*
        EOT
        chmod +x publish.sh

        docker pull $IMAGE
        docker run --rm -v $GITHUB_WORKSPACE:/scratch -v $HOME:/scratch-home $IMAGE /scratch/publish.sh
        rm -f $GITHUB_WORKSPACE/publish.sh
