name: Nightly Integration Test

on:
  schedule:
    - cron: "0 9 * * *"

  workflow_dispatch:


jobs:
  make_nightly_tag:
    name: create nightly tag
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.create_nightly_tag.outputs.nightly_tag }} 
    defaults:
      run:
        shell: bash
    steps:
      - id: create_nightly_tag
        run: |
          date_tag=$(date +%y%m%d)
          echo "nightly_tag=NFD_PROD4_${date_tag}_A9"  >>  "$GITHUB_OUTPUT"
          cat "$GITHUB_OUTPUT"

  integration_test:
    name: integration_test
    runs-on: isc01
    needs: make_nightly_tag
    defaults:
      run:
        shell: bash

    steps:

    - name: Checkout daqsystemtest
      uses: actions/checkout@v4
      with:
        repository: DUNE-DAQ/daqsystemtest
        path: daqsystemtest
    
    - name: setup release and run test
      env:
        NIGHTLY_TAG: ${{needs.make_nightly_tag.outputs.tag}}
      run: |
          DET=fd
          mkdir -p $GITHUB_WORKSPACE/integration_test_$NIGHTLY_TAG
          cd $GITHUB_WORKSPACE/integration_test_$NIGHTLY_TAG
          source /cvmfs/dunedaq.opensciencegrid.org/setup_dunedaq.sh
          setup_dbt latest|| true
          dbt-setup-release -n $NIGHTLY_TAG
          #dbt-setup-release -n last_${DET}daq
          export PATH=$HOME/bin:$PATH
          type get-ticket.sh && get-ticket.sh
          rm -f $GITHUB_WORKSPACE/test-results.xml
          pytest --junit-xml=$GITHUB_WORKSPACE/minimal-test-results.xml $GITHUB_WORKSPACE/daqsystemtest/integtest/minimal_system_quick_test.py
          pytest --junit-xml=$GITHUB_WORKSPACE/fake-data-test-results.xml $GITHUB_WORKSPACE/daqsystemtest/integtest/fake_data_producer_test.py
          pytest --junit-xml=$GITHUB_WORKSPACE/long-readout-test-results.xml $GITHUB_WORKSPACE/daqsystemtest/integtest/long_window_readout_test.py
          pytest --junit-xml=$GITHUB_WORKSPACE/small-footprint-test-results.xml $GITHUB_WORKSPACE/daqsystemtest/integtest/small_footprint_quick_test.py
          cd $GITHUB_WORKSPACE
          rm -rf integration_test_$NIGHTLY_TAG
          rm -rf daqsystemtest

    - name: Surface failing tests
      if: always()
      uses: pmeier/pytest-results-action@8104ed7b3d3ba4bb0d550e406fc26aa756630fcc
      with:
        path: ${{ github.workspace }}/*-test-results.xml
        summary: true
        display-options: fEX
        fail-on-empty: true
