name: Poll CVMFS for release

on:
  workflow_dispatch:
    inputs:
      release-tag:
        type: string
        description: 'Release tag pattern to check for on CVMFS'
      max-tries:
        type: string
        description: 'Maximum number of polling attempts before timing out'
        default: '60'
      interval:
        type: string
        description: 'Interval in seconds between polling attempts'
        default: '60'
      send-slack-message:
        type: string
        description: 'Whether to notify #daq-release-notifications of completion.'
        default: 'yes'
  workflow_call:
    inputs:
      release-tag:
        type: string
        description: 'Release tag pattern to check for on CVMFS'
      max-tries:
        type: string
        description: 'Maximum number of polling attempts before timing out'
        default: '60'
      interval:
        type: string
        description: 'Interval in seconds between polling attempts'
        default: '60'
      send-slack-message:
        type: string
        description: 'Whether to notify #daq-release-notifications of completion.'
        default: 'yes'

jobs:
  poll_cvmfs:
    runs-on: daq
    timeout-minutes: 90
    steps:
    - name: Checkout daq-release
      uses: actions/checkout@v6
      with:
        path: daq-release-cvmfs-poll
        ref: amogan/poll_cvmfs_workflow
    - name: poll_release
      run: |
        ./daq-release-cvmfs-poll/scripts/github-ci/poll_cvmfs_for_release.sh \
              ${{ inputs.release-tag }} \
              ${{ inputs.interval }} \
              ${{ inputs.max-tries }}

  send_slack_message:
    if: |
      (success() || failure()) &&
      ((github.event_name != 'workflow_dispatch') ||
      (github.event_name == 'workflow_dispatch' && 
      (github.event.inputs.send-slack-message == 'yes' || inputs.send-slack-message == 'yes')))
    needs: [poll_cvmfs]
    uses: ./.github/workflows/slack-notification.yml
    with:
      release_tag: ${{ inputs.release-tag }}
    secrets: 
      #slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
      slack_webhook_url: ${{ secrets.SLACK_TEST_WEBHOOK }}

  cleanup:
    runs-on: daq
    needs: poll_cvmfs
    if: always()
    steps:
    - name: Remove directories
      run: |
        rm -rf daq-release-cvmfs-poll

