name: Poll CVMFS for release

on:
  workflow_dispatch:
    inputs:
      release-tag:
        type: string
        description: 'Release tag pattern to check for on CVMFS'
      max-tries:
        type: string
        description: 'Maximum number of polling attempts before timing out'
        default: '60'
      interval:
        type: string
        description: 'Interval in seconds between polling attempts'
        default: '60'
      send-slack-message:
        type: string
        description: 'Whether to notify #daq-release-notifications of completion.'
        default: 'yes'
  workflow_call:
    inputs:
      release-tag:
        type: string
        description: 'Release tag pattern to check for on CVMFS.'
      max-tries:
        type: string
        description: 'Maximum number of polling attempts before timing out'
        default: '60'
      interval:
        type: string
        description: 'Interval in seconds between polling attempts'
        default: '60'
      send-slack-message:
        type: string
        description: 'Whether to notify #daq-release-notifications of completion.'
        default: 'yes'

jobs:
  poll_cvmfs:
    runs-on: ubuntu-latest
    timeout-minutes: 90
    steps:
    - uses: cvmfs-contrib/github-action-cvmfs@v5
      with:
        cvmfs_repositories: 'dunedaq.opensciencegrid.org, 
                             dunedaq-development.opensciencegrid.org'
    - name: Checkout daq-release
      uses: actions/checkout@v6
      with:
        path: daq-release-cvmfs-poll
    - name: poll_release
      run: |
        ./daq-release-cvmfs-poll/scripts/github-ci/poll_cvmfs_for_release.sh \
              ${{ inputs.release-tag }} \
              ${{ inputs.interval }} \
              ${{ inputs.max-tries }}

  send_slack_message:
    if: |
      (success() || failure()) &&
      ((github.event_name != 'workflow_dispatch') ||
      (github.event_name == 'workflow_dispatch' && 
      (github.event.inputs.send-slack-message == 'yes' || inputs.send-slack-message == 'yes')))
    needs: [poll_cvmfs]
    uses: ./.github/workflows/slack-notification.yml
    with:
      release_tag: ${{ inputs.release-tag }}
      caller: 'Poll CVMFS for release'
    secrets: 
      slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}


