name: Slack Notification

on:
  workflow_call:
    inputs:
      integtest_xml_dir:
        type: string
        default: ''
        description: Optional path to directory containing junit xml files output by pytests.
      integtest_log_dir:
        type: string
        default: ''
        description: Optional path to directory containing the full pytest output.
    secrets:
      slack_webhook_url:
        required: true

jobs:
  generate_and_send_slack_message:
    runs-on: daq
    steps:
    - name: Checkout daq-release
      uses: actions/checkout@v4
      with:
        repository: DUNE-DAQ/daq-release
        path: daq-release-slack-message
    - name: Get workflow failures from GitHub API
      run: |
        WORKFLOW_DETAILS=$(gh api /repos/${{ github.repository }}/actions/runs/${{ github.run_id }})

        WORKFLOW_NAME=$(echo "$WORKFLOW_DETAILS" | jq -r '.name')
        ACTOR_LOGIN=$(echo "$WORKFLOW_DETAILS" | jq -r '.actor.login')
        EVENT_TYPE=$(echo "$WORKFLOW_DETAILS" | jq -r '.event')
        HTML_URL=$(echo "$WORKFLOW_DETAILS" | jq -r '.html_url')

        # Get failed jobs and merge with workflow details
        gh api /repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/jobs \
        | jq --arg workflow "$WORKFLOW_NAME" --arg actor "$ACTOR_LOGIN" --arg event "$EVENT_TYPE" --arg html_url "$HTML_URL" \
          '{workflow: $workflow, actor: $actor, event: $event, html_url: $html_url, failed_jobs: [ .jobs[] | select(.conclusion != "success") | {job: .name, conclusion: .conclusion, steps: [.steps[] | select(.conclusion == "failure") | {name: .name}]}]}' \
        | tee failed_jobs.json
    - name: Parse GitHub API output
      run: |
        python daq-release-slack-message/scripts/github-ci/slack_payload_generator.py \
               --api-output failed_jobs.json \
               --junit-xml-dir ${{ inputs.integtest_xml_dir }} \
               --pytest-log-dir ${{ inputs.integtest_log_dir }}
        cat slack_payload.json
    - name: Send Slack Message
      uses: slackapi/slack-github-action@v2.0.0
      with:
        webhook: ${{ secrets.slack_webhook_url }}
        webhook-type: incoming-webhook
        payload-file-path: "./slack_payload.json"
        payload-templated: true
        errors: true
    - name: Cleanup files
      run: |
        rm failed_jobs.json slack_payload.json
        rm -rf daq-release-slack-message