name: Slack Notification

on:
  workflow_call:
    inputs:
      workflow_success: 
        required: true
        type: boolean
    secrets:
      slack_webhook_url:
        required: true

jobs:
  checkout_daq_release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout daq-release
      uses: actions/checkout@v4
      with:
        repository: DUNE-DAQ/daq-release
        path: daq-release
        ref: amogan/improved_slack_messaging
  check_for_payload:
    name: Check payload exists
    needs: checkout_daq_release
    runs-on: ubuntu-latest
    steps:
    - name: ls for payload
      run: |
        echo -e "Currently in $(pwd). Contents:\n $(ls)"
        echo "Github workspace: ${{ github.workspace }}"
        echo "Github workspace contents: $(ls ${{ github.workspace }})"
        echo -e "Try to cat ./daq-release/.github/workflows/slack-notification-success.json"...
        cat ./daq-release/.github/workflows/slack-notification-success.json || true
        echo -e "Try to cat $GITHUB_WORKSPACE/daq-release/.github/workflows/slack-notification-success.json"...
        cat ${{ github.workspace }}/daq-release/.github/workflows/slack-notification-success.json || true
  notify:
    name: Send Slack Notification
    needs: checkout_daq_release
    runs-on: ubuntu-latest
    steps:
    - name: Send failure message to Slack
      uses: slackapi/slack-github-action@v2.0.0
      if: ${{ ! inputs.workflow_success }}
      with:
        webhook: ${{ secrets.slack_webhook_url }}
        webhook-type: incoming-webhook
        # For posting a rich message using Block Kit
        payload: |
          {
            "blocks": [
              {
                "type": "header",
                "text": {
                  "type": "plain_text",
                  "text": ":rotating_light: Failed: ${{ github.workflow }} :rotating_light:",
                  "emoji": true
                }
              },
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "Full report: <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|link>."
                }
              }
            ]
          }
    - name: Send success message to Slack
      uses: slackapi/slack-github-action@v2.0.0
      if: ${{ inputs.workflow_success }}
      with:
        webhook: ${{ secrets.slack_webhook_url }}
        webhook-type: incoming-webhook
        payload-file-path: "./daq-release/.github/workflows/slack-notification-success.json"
        payload-templated: true