name: Slack Notification

on:
  workflow_call:
    inputs:
      workflow_success: 
        required: true
        type: boolean
    secrets:
      slack_webhook_url:
        required: true

jobs:
  check_for_payload:
    runs-on: ubuntu-latest
    steps:
    - name: ls for payload
      run: |
        echo -e "Currently in $(pwd). Contents:\n $(ls)"
        echo -e "Try to cat ./.github/workflows/slack-notification-success.json"...
        cat ./.github/workflows/slack-notification-success.json
        echo -e "Try to cat ./daq-release-integtest/.github/workflows/slack-notification-success.json"...
        cat ./daq-release-integtest.github/workflows/slack-notification-success.json
  notify:
    name: Send Slack Notification
    runs-on: ubuntu-latest
    steps:
    - name: Send failure message to Slack
      uses: slackapi/slack-github-action@v2.0.0
      if: ${{ ! inputs.workflow_success }}
      with:
        webhook: ${{ secrets.slack_webhook_url }}
        webhook-type: incoming-webhook
        # For posting a rich message using Block Kit
        payload: |
          {
            "blocks": [
              {
                "type": "header",
                "text": {
                  "type": "plain_text",
                  "text": ":rotating_light: Failed: ${{ github.workflow }} :rotating_light:",
                  "emoji": true
                }
              },
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "Full report: <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|link>."
                }
              }
            ]
          }
    - name: Send success message to Slack
      uses: slackapi/slack-github-action@v2.0.0
      if: ${{ inputs.workflow_success }}
      with:
        webhook: ${{ secrets.slack_webhook_url }}
        webhook-type: incoming-webhook
        payload-file-path: "./.github/workflows/slack-notification-success.json"
        payload-templated: true