name: Test Workflow

on:
  workflow_dispatch:

jobs:
  build_the_develop_release_spack:
    name: build_dev_release_spack
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/dune-daq/sl7-minimal:latest
      volumes:
        - pypi-repo:/cvmfs/dunedaq.opensciencegrid.org/pypi-repo
    services:
      cvmfs:
        image: ghcr.io/dune-daq/pypi-repo:latest
        volumes:
          - pypi-repo:/cvmfs/dunedaq.opensciencegrid.org/pypi-repo
    defaults:
      run:
        shell: bash

    steps:
    - name: check pypi-repo existence
      run: |
        ls /cvmfs
        ls /cvmfs/*
        ls /cvmfs/*/*
        printenv

  test_cvmfs:
    name: test_cvmfs
    runs-on: ubuntu-latest

    steps:
    - uses: cvmfs-contrib/github-action-cvmfs@v2

    - name: check pypi-repo existence
      run: |
        ls /cvmfs/dunedaq.opensciencegrid.org/

    - name: start docker container with bind mount cvmfs
      run: |
        mkdir -p $GITHUB_WORKSPACE/cvmfs_dunedaq_dev
        echo "#!/bin/bash" > $GITHUB_WORKSPACE/cvmfs_dunedaq_dev/test.sh
        echo "ls /cvmfs/dunedaq.opensciencegrid.org" >> $GITHUB_WORKSPACE/cvmfs_dunedaq_dev/test.sh
        echo "ls /cvmfs/dunedaq-development.opensciencegrid.org" >> $GITHUB_WORKSPACE/cvmfs_dunedaq_dev/test.sh
        chmod +x $GITHUB_WORKSPACE/cvmfs_dunedaq_dev/test.sh
        docker run --rm -v /cvmfs/dunedaq.opensciencegrid.org:/cvmfs/dunedaq.opensciencegrid.org -v $GITHUB_WORKSPACE/cvmfs_dunedaq_dev:/cvmfs/dunedaq-development.opensciencegrid.org ghcr.io/dune-daq/sl7-minimal:latest /cvmfs/dunedaq-development.opensciencegrid.org/test.sh
