name: Test Workflow

on:
  workflow_dispatch:

jobs:
  build_the_develop_release_spack:
    name: build_dev_release_spack
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/dune-daq/sl7-minimal:latest
      volumes:
        - pypi-repo:/cvmfs/dunedaq.opensciencegrid.org/pypi-repo
    services:
      cvmfs:
        image: ghcr.io/dune-daq/sl7-externals:latest
        volumes:
          - pypi-repo:/cvmfs/dunedaq.opensciencegrid.org/pypi-repo
    defaults:
      run:
        shell: bash

    steps:
    - name: check pypi-repo existence
      run: |
        ls /cvmfs
        ls /cvmfs/*
        ls /cvmfs/*/*
        printenv
