name: Test Single Pkg Workflow

on:
  workflow_dispatch:
    inputs:
      pkg-name:
        description: 'single packge CI'
        default: 'appfwk'

jobs:

  build_single_pkg:
    name: build single pkg
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - image: "dunedaq/sl7-minimal:spack-dev"
            os_name: "c7"

    steps:
    - uses: cvmfs-contrib/github-action-cvmfs@v2

    - name: change dir permission
      run: |
        sudo chmod -R ugo+rwx /var/lib/cvmfs

    - name: Cache cvmfs cache
      id: cvmfs_cache
      uses: actions/cache@v3
      with:
        path: /var/lib/cvmfs
        key: cvmfscache

    - name: Checkout pkg
      uses: actions/checkout@v3
      with:
        repository: DUNE-DAQ/${{ github.event.inputs.pkg-name }}
        path: scratch/sourcecode/${{ github.event.inputs.pkg-name }}

    - name: start docker container with bind mount cvmfs
      run: |

        cd $GITHUB_WORKSPACE/scratch
        cat << EOT > build_pkg.sh
        #!/bin/bash
        
        cd /scratch
        source /cvmfs/dunedaq.opensciencegrid.org/tools/dbt/v5.0.9/env.sh
        dbt-create -c -n last_successful dev-${{ matrix.os_name }}
        cd dev-${{ matrix.os_name }}
        source dbt-env.sh
        dbt-workarea-env || true
        spack unload ${{ github.event.inputs.pkg-name }}
        mv /scratch/sourcecode/* sourcecode
        dbt-build --lint
        dbt-workarea-env
        EOT
        chmod +x build_pkg.sh

        docker run --rm -v /cvmfs:/cvmfs:shared -v $GITHUB_WORKSPACE/scratch:/scratch ghcr.io/dune-daq/sl7-spack:latest /scratch/build_pkg.sh

    - name: upload build log file
      uses: actions/upload-artifact@v2
      with:
        name: spack_build_log_${{ matrix.os_name }}
        path: ${{ github.workspace }}/scratch/dev-${{ matrix.os_name }}/log/build*.log

    - name: upload linter output file
      uses: actions/upload-artifact@v2
      with:
        name: spack_linting_log_${{ matrix.os_name }}
        path: ${{ github.workspace }}/scratch/dev-${{ matrix.os_name }}/log/linting*

    - name: change dir permission again
      run: |
        sudo chmod -R ugo+rwx /var/lib/cvmfs

