name: Run Unit Tests on a Given Release

permissions:
  contents: read

on:
  workflow_call:
    inputs:
      release_tag:
        type: string
        required: true
        description: Name of the release used in the caller workflow.
      upload_logs:
        type: string
        required: false
        default: 'no'
        description: Whether to upload unit test summary logs.
      send-slack-message:
          description: 'whether to send a message to #daq-release-notifications on completion'
          type: string
          default: 'no'
  workflow_dispatch:
    inputs:
      release_tag:
        type: string
        required: true
        description: Name of the release to unit test
      upload_logs:
        required: false
        default: 'yes'
        description: Whether to upload unit test summary logs.
      send-slack-message:
          description: 'whether to send a message to #daq-release-notifications on completion'
          type: string
          default: 'no'

jobs:
  run_unittests:
    name: Run unit tests
    runs-on: daq
    timeout-minutes: 30
    env:
      RELEASE_TAG: ${{ inputs.release_tag }}
    defaults:
      run:
        shell: bash
    steps:
    - name: Checkout daq-release
      uses: actions/checkout@v6
      with:
        path: daq-release-unittests
    - name: Determine release type
      id: release_type
      uses: ./daq-release-unittests/.github/actions/get-release-type
      with:
        TAG: ${{ inputs.release_tag }}
    - name: Create build area
      env:
        RELEASE_TYPE: ${{ steps.release_type.outputs.type }}
        DBT_ARGS: ${{ steps.release_type.outputs.dbt_args }}
        COREDAQ_MANIFEST: ${{ steps.release_type.outputs.coredaq_manifest }}
        FDDAQ_MANIFEST: ${{ steps.release_type.outputs.fddaq_manifest }}
      run: |
        source /cvmfs/dunedaq.opensciencegrid.org/setup_dunedaq.sh
        setup_dbt latest

        dbt-create "$DBT_ARGS" "$RELEASE_TAG"

        cd "$RELEASE_TAG"
        source env.sh

        cd ../daq-release-unittests/scripts
        #./checkout-daq-package.py -i ../$COREDAQ_MANIFEST -a -o ${DBT_AREA_ROOT}/sourcecode
        #./checkout-daq-package.py -i ../$FDDAQ_MANIFEST -a -o ${DBT_AREA_ROOT}/sourcecode
        ./checkout-daq-package.py -p hdf5libs -i ../$COREDAQ_MANIFEST -o ${DBT_AREA_ROOT}/sourcecode
        ./checkout-daq-package.py -p flxlibs -i ../$FDDAQ_MANIFEST -o ${DBT_AREA_ROOT}/sourcecode
        echo "DBT_AREA_ROOT=$DBT_AREA_ROOT" >> "$GITHUB_ENV"
    - name: Run unit tests
      id: unit_tests
      run: |
        cd $DBT_AREA_ROOT/
        source env.sh
        spack load dbe
        dbt-workarea-env
        dbt-build --unittest
        log_summary_file=$(ls $DBT_AREA_ROOT/log/unit_tests_*/*_summary.log)
        ../daq-release-unittests/scripts/github-ci/parse_unit_test_summary.sh $log_summary_file | tee $GITHUB_STEP_SUMMARY
        echo "unit_test_summary=$log_summary_file" >> "$GITHUB_OUTPUT"
    - name: Upload summary log
      # Handle both workflow_call and workflow_dispatch cases
      if: ${{ inputs.upload_logs == 'yes' || github.event.inputs.upload_logs == 'yes' }}
      uses: actions/upload-artifact@v7
      with:
        if-no-files-found: error
        name: unit_test_summary
        path: ${{ steps.unit_tests.outputs.unit_test_summary }}
    - name: Remove files
      if: always()
      run: |
        rm -rf $RELEASE_TAG || true
        rm -rf ${{ github.workspace }}/daq-release-unittests || true

  send_slack_message:
    if: (success() || failure()) && (inputs.send-slack-message == 'yes' && github.event_name == 'workflow_dispatch')
    needs: [run_unittests]
    uses: ./.github/workflows/slack-notification.yml
    with:
      release_tag: ${{ inputs.release_tag }}
    secrets: 
      slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
