name: Run Unit Tests on a Given Release

on:
  workflow_call:
    inputs:
      release_tag:
        type: string
        required: true
        description: Name of the release used in the caller workflow.
      upload_logs:
        type: string
        required: false
        default: 'no'
        description: Whether to upload unit test summary logs.
      send-slack-message:
          description: 'whether to send a message to #daq-release-notifications on completion'
          type: string
          default: 'no'
  workflow_dispatch:
    inputs:
      release_tag:
        type: string
        required: true
        description: Name of the release to unit test
      upload_logs:
        required: false
        default: 'yes'
        description: Whether to upload unit test summary logs.
      send-slack-message:
          description: 'whether to send a message to #daq-release-notifications on completion'
          type: string
          default: 'no'

jobs:
  run_unittests:
    name: Run unit tests
    runs-on: daq
    timeout-minutes: 30
    defaults:
      run:
        shell: bash
    steps:
    - name: Checkout daq-release
      uses: actions/checkout@v4
      with:
        path: daq-release-unittests
    - name: Determine release type
      env:
        RELEASE_TAG: ${{ inputs.release_tag }}
      run: |
        RELEASE_TYPE=""
        echo "RELEASE_TAG: $RELEASE_TAG"
        if [[ "$RELEASE_TAG" == NFD* ]]; then
          RELEASE_TYPE="nightly"
        elif [[ "$RELEASE_TAG" == *rc* ]]; then
          RELEASE_TYPE="candidate"
        elif [[ "$RELEASE_TAG" =~ ^fddaq-v[0-9]+\.[0-9]+\.[0-9]+-a9 ]]; then
          RELEASE_TYPE="stable"
        else
          echo "Could not determine release type. Exiting..."
          exit 1
        fi

        echo "RELEASE_TAG=$RELEASE_TAG" >> $GITHUB_ENV
        echo "RELEASE_TYPE=$RELEASE_TYPE" >> $GITHUB_ENV

    - name: Create build area
      run: |
        source /cvmfs/dunedaq.opensciencegrid.org/setup_dunedaq.sh
        setup_dbt latest
        if [[ "$RELEASE_TYPE" == "nightly" ]]; then
          dbt-create -n "$RELEASE_TAG"
        elif [[ "$RELEASE_TYPE" == "candidate" ]]; then
          dbt-create -b candidate "$RELEASE_TAG"
        else
          dbt-create "$RELEASE_TAG" "$RELEASE_TAG"
        fi
        cd "$RELEASE_TAG"
        source env.sh

        if [[ "$RELEASE_TYPE" == "nightly" ]]; then
          VERSION_TAG="develop"
        else
          # To find the correct release manifest, extract vX.Y.Z from the release name
          VERSION_TAG=$(echo "$RELEASE_TAG" | grep -oP 'v[0-9]+\.[0-9]+\.[0-9]+')
        fi
        echo "VERSION_TAG: $VERSION_TAG"

        cd ../daq-release-unittests/scripts
        ./checkout-daq-package.py -i ../configs/coredaq/coredaq-${VERSION_TAG}/release.yaml -a -o ${DBT_AREA_ROOT}/sourcecode
        ./checkout-daq-package.py -i ../configs/fddaq/fddaq-${VERSION_TAG}/release.yaml -a -o ${DBT_AREA_ROOT}/sourcecode
        #./checkout-daq-package.py -p hdf5libs -b develop -i ../configs/coredaq/coredaq-${VERSION_TAG}/release.yaml -o ${DBT_AREA_ROOT}/sourcecode
        #./checkout-daq-package.py -p flxlibs -b develop -i ../configs/fddaq/fddaq-${VERSION_TAG}/release.yaml -o ${DBT_AREA_ROOT}/sourcecode
        echo "DBT_AREA_ROOT=$DBT_AREA_ROOT" >> "$GITHUB_ENV"
    - name: Run unit tests
      id: unit_tests
      run: |
        cd $DBT_AREA_ROOT/
        source env.sh
        spack load dbe
        dbt-workarea-env
        dbt-build --unittest
        log_summary_file=$(ls $DBT_AREA_ROOT/log/unit_tests_*/*_summary.log)
        ../daq-release-unittests/scripts/github-ci/parse_unit_test_summary.sh $log_summary_file | tee $GITHUB_STEP_SUMMARY
        echo "unit_test_summary=$log_summary_file" >> "$GITHUB_OUTPUT"
    - name: Upload summary log
      # Handle both workflow_call and workflow_dispatch cases
      if: ${{ inputs.upload_logs == 'yes' || github.event.inputs.upload_logs == 'yes' }}
      uses: actions/upload-artifact@v5
      with:
        if-no-files-found: error
        name: unit_test_summary
        path: ${{ steps.unit_tests.outputs.unit_test_summary }}

  send_slack_message:
    if: (success() || failure()) && (inputs.send-slack-message == 'yes' && github.event_name == 'workflow_dispatch')
    needs: [run_unittests]
    uses: ./.github/workflows/slack-notification.yml
    with:
      release_tag: ${{ inputs.release_tag }}
    secrets: 
      slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}

  cleanup_files:
    if: always()
    needs: run_unittests
    runs-on: daq
    env:
      RELEASE_TAG: ${{ inputs.release_tag }}
    steps:
    - name: Remove files
      run: |
        rm -rf $RELEASE_TAG
        rm -rf ${{ github.workspace }}/daq-release-unittests
