name: Poll CVMFS for release

on:
  workflow_dispatch:
    inputs:
      tag-pattern:
        type: string
        description: 'Nightly tag pattern to check for on CVMFS (default: "NFD_*")'
        default: 'NFD_*'
  workflow_call:
    inputs:
      tag-pattern:
        type: string
        description: 'Nightly tag pattern to check for on CVMFS (default: "NFD_*")'
        default: 'NFD_*'

jobs:
  wait_for_cvmfs_publication:
    runs-on: daq
    timeout-minutes: 90
    steps:
    - name: Check for release on CVMFS
      run: |
        ~/wait_for_cvmfs_publication.sh \
          --tag-pattern "NFD_*" \
          --max-tries 3 \
          --interval 60 \

