name: Weekly code coverage workflow

on:
  workflow_dispatch:
    inputs:
      send-slack-message:
        description: 'whether to send a message to #daq-release-notifications on completion'
        default: 'no'
  schedule:
    - cron: "0 18 * * 0"

jobs:
  make_nightly_tag:
    name: create nightly tag
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.create_nightly_tag.outputs.nightly_tag }} 
    defaults:
      run:
        shell: bash
    steps:
      - id: create_nightly_tag
        run: |
          date_tag=$(date +%y%m%d)
          echo "nightly_tag=NFD_DEV_${date_tag}_A9"  >>  "$GITHUB_OUTPUT"
          cat "$GITHUB_OUTPUT"

  generate_code_coverage_report:
    name: Generate code coverage report
    runs-on: daq
    needs: make_nightly_tag
    timeout-minutes: 60
    outputs:
      coverage_results_dir: ${{ steps.run_lcov.outputs.results_dir }}
    defaults:
      run:
        shell: bash
    steps:
    - name: Checkout daq-release
      uses: actions/checkout@v4
      with:
        path: daq-release-lcov
    - name: Create build area
      id: create_build_area
      run: |
        source /cvmfs/dunedaq.opensciencegrid.org/setup_dunedaq.sh
        setup_dbt latest_v5
        dbt-create -n ${{ needs.make_nightly_tag.outputs.tag }}
        cd ${{ needs.make_nightly_tag.outputs.tag }}
        source env.sh
        cd ../daq-release-lcov/scripts
        #./checkout-daq-package.py -i ../configs/coredaq/coredaq-develop/release.yaml -a -o ${DBT_AREA_ROOT}/sourcecode
        #./checkout-daq-package.py -i ../configs/fddaq/fddaq-develop/release.yaml -a -o ${DBT_AREA_ROOT}/sourcecode
        ./checkout-daq-package.py -p hdf5libs -b develop -i ../configs/coredaq/coredaq-develop/release.yaml -o ${DBT_AREA_ROOT}/sourcecode
        ./checkout-daq-package.py -p flxlibs -b develop -i ../configs/fddaq/fddaq-develop/release.yaml -o ${DBT_AREA_ROOT}/sourcecode
        echo "DBT_AREA_ROOT=${DBT_AREA_ROOT}" >> "$GITHUB_ENV"
    - name: Run dbt-lcov.sh
      id: run_lcov
      run: |
        cd $DBT_AREA_ROOT/
        echo "Where am I? $(pwd)"
        echo "DBT_AREA_ROOT in lcov step: $DBT_AREA_ROOT"
        source env.sh
        dbt-workarea-env
        # spack load dbe
        dbt-lcov.sh
        echo "results_dir=${DBT_AREA_ROOT}/code_coverage_results/html" >> "$GITHUB_OUTPUT"
    - name: Upload html output as artifact
      uses: actions/upload-artifact@v4
      with:
        if-no-files-found: error
        name: code_coverage
        path: ${{ steps.run_lcov.outputs.results_dir }}

  send_slack_message:
    if: (github.event_name != 'workflow_dispatch') || (github.event_name == 'workflow_dispatch' && github.event.inputs.send-slack-message == 'yes')
    needs: generate_code_coverage_report
    uses: ./.github/workflows/slack-notification.yml
    secrets: 
      slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}

  cleanup_test_area:
    runs-on: daq
    if: always()
    needs: [make_nightly_tag, generate_code_coverage_report]
    steps:
      - name: Remove test directory
        run: |
          rm -rf daq-release-lcov
          rm -rf ${{ needs.make_nightly_tag.outputs.tag }}